from collections import defaultdict
from dataclasses import dataclass
from typing import DefaultDict, Dict, Iterable, List, Tuple


@dataclass(frozen=True)
class PhraseRule:
    item_id: str
    questionnaire: str
    phrases: Tuple[str, ...]
    score_hint: int
    rationale: str


RULES: List[PhraseRule] = [
    PhraseRule(
        "phq_q1_anhedonia",
        "PHQ9",
        (
            "don't enjoy anything",
            "nothing feels enjoyable",
            "less interest in things",
            "interest has gone down",
            "things i usually care about feel flat",
            "things i usually care about feel flat before i even start them",
            "stuff i care about feels flat",
            "stuff i care about feels flat and heavy",
            "things i care about feel flat",
            "what i care about feels flat",
            "everything feels flat underneath",
            "feels flat underneath",
            "disconnected feel ho raha hai",
            "disconnected feel ho rahi hai",
            "flat feel hoti hai",
            "flat feel hoti hain",
            "flat feel hota hai",
            "flat lagti hain",
            "flat lagta hai",
            "jo cheezein pehle achhi lagti thi ab flat feel hoti hain",
            "jo cheezen pehle achhi lagti thi ab flat feel hoti hain",
            "जो चीज़ें पहले अच्छी लगती थीं अब उनमें बहुत कम महसूस होता है",
            "जिन चीजों में पहले मन लगता था उनमें अब रुचि कम हो गई है",
            "बहुत कम महसूस होता है",
            "kuch feel nahi hota",
            "unse kuch feel nahi hota",
            "kar bhi leta hoon but unse kuch feel nahi hota",
            "gaane sunne ka mann nahi karta",
            "mann hi nahi karta",
            "man nahi karta",
            "mann nahi lagta",
            "man nahi lagta",
            "kuch accha nahi lagta",
            "मन नहीं करता",
            "मन ही नहीं करता",
            "किसी काम में मन नहीं लगता",
            "किसी काम में मन नहीं लगता है",
            "काम में मन नहीं लगता",
            "काम में मन नहीं लगता है",
            "किसी काम से मन हट जाना",
            "मन हट जाना",
            "मन पहले से ही हट जाता है",
            "काम करने की इच्छा नहीं होती",
            "काम करने की इच्छा ही नहीं होती",
            "कोई काम करने की इच्छा नहीं होती",
            "कोई काम करने की इच्छा ही नहीं होती",
            "किसी काम की इच्छा नहीं होती",
            "कोई काम करने की इच्छा करती ही नहीं है",
            "काम करने की इच्छा करती ही नहीं है",
            "कुछ अच्छा नहीं लगता",
            "cannot make myself care enough",
            "usually say maybe later",
            "skip basketball",
            "doston se baat karne ka mann nahi karta",
            "friends se baat karne ka mann nahi karta",
            "coding ka mann nahi karta",
            "people se milne ka man nahi karta",
            "लोगों से मिलने का मन नहीं करता",
            "bed se uthne ka mann nahi karta",
            "kaam start karne ka bilkul mann nahi karta",
            "काम शुरू करने का मन नहीं करता",
            "कोई काम शुरू करने का मन नहीं करता",
            "delay starting things",
            "keep delaying starting things",
            "put off starting things",
            "काम शुरू करने से पहले ही मन हट जाता है",
            "शुरू करने से पहले ही मन हट जाता है",
            "जो चीज़ें पहले अच्छी लगती थीं उनमें शुरू करने से पहले ही मन हट जाता है",
            "kaam shuru karne se pehle hi mann hat jata hai",
            "karne se pehle hi mann hat jata hai",
            "jo cheezein pehle achhi lagti thi unmein start karne se pehle hi mann hat jata hai",
            "kisi kaam se mann hat jana",
            "mann hat jana",
            "mann pehle se hi hat jata hai",
            "pulling away from people",
            "ignore texts",
            "ignore messages",
            "reply talta rehta hoon",
            "reply talti rehti hoon",
            "distance bana leta hoon",
            "interest bhi kam ho gaya hai",
            "रुचि कम हो गई है",
            "ruchi kam ho gayi hai",
            "motivation low rehti hai",
            "motivation stays low",
            "mood crash ho jata",
            "motions mein chalta rehta hoon",
            "motions mein chalta rehti hoon",
            "bas motions mein chalta rehta hoon",
        ),
        2,
        "reduced interest",
    ),
    PhraseRule(
        "phq_q2_low_mood",
        "PHQ9",
        (
            "feel low",
            "feel low through most of the day",
            "low through most of the day",
            "feel down",
            "flat and heavy",
            "heavy and blank",
            "heavy aur thoda blank",
            "flat aur low lagta hai",
            "flat aur low lagti hai",
            "zyada flat aur low lagta hai",
            "zyada flat aur low lagti hai",
            "low aur disconnected feel ho raha hai",
            "low aur disconnected feel ho rahi hai",
            "kaafi time se low aur disconnected feel ho raha hai",
            "kaafi time se low aur disconnected feel ho rahi hai",
            "empty most days",
            "blank feel hota",
            "udaas rehta",
            "bahut udaas",
            "khali khali lagta",
            "खालीपन",
            "खालीपन है",
            "उदासी आती है",
            "उदासी आ जाती है",
            "उदासी",
            "उदासी बनी रहती है",
            "वर्तमान देखता हूं तो उदासी आती है",
            "ज़्यादातर दिन भारी लगते हैं",
            "ज्यादातर दिन भारी लगते हैं",
            "दिन भारी लगते हैं",
            "दिन अपने आप में भारी लगते हैं",
            "vartaman dekhta hoon to udaasi aati hai",
            "udaasi aati hai",
            "mood bhi low rehta hai",
            "mood low rehta hai",
            "दिन भारी लगता है",
            "udasi",
            "udasi zyada lagti hai",
            "ज़्यादा उदासी",
            "ज्यादा उदासी",
            "present dekh ke heavy lagta hai",
            "present dekh ke heavy lagti hai",
            "present feels heavy",
            "abhi sab bhaari lagta hai",
            "अभी सब भारी लगता है",
            "वर्तमान देखता हूं तो मन भारी लगता है",
            "वर्तमान देखता हूँ तो मन भारी लगता है",
            "अंदर बहुत रोना आता है",
            "बहुत रोना आता है",
            "वॉशरूम में बैठकर रोता हूँ",
            "मन भारी लगता है",
            "feel flat most of the day",
            "everything feels flat underneath",
            "feels flat underneath",
            "emotionally flat underneath",
            "sab flat feel hota hai",
            "sab flat feel hoti hai",
            "sab flat feel hota rehta hai",
            "andar se sab flat lagta hai",
            "andar se sab flat sa lagta hai",
            "andar se sab fika lagta hai",
            "अंदर से सब फीका लगता है",
            "अंदर से सब फीका सा लगता है",
            "अंदर से सब सपाट लगता है",
            "drop in my stomach",
            "andar bahut rona aata",
            "pura mood crash ho jata",
            "washroom mein baithkar rota",
        ),
        2,
        "low mood",
    ),
    PhraseRule(
        "phq_q3_sleep",
        "PHQ9",
        (
            "can't sleep",
            "sleeping badly",
            "sleep is bad",
            "sleep is off",
            "sleep has been broken",
            "sleep has been broken for the last couple of weeks",
            "sleep is broken",
            "broken sleep",
            "sleep keeps breaking",
            "sleep keeps getting interrupted",
            "sleep schedule is messed up",
            "sleep has been patchy",
            "sleep has shifted later",
            "sleep shifted later",
            "sleep has shifted",
            "sleep shifted",
            "sleep ka pattern off hai",
            "sleep pattern off hai",
            "sleep thodi patchy hai",
            "sleep patchy hai",
            "keep waking up",
            "sleep break hoti",
            "sleep break hoti rehti",
            "sleep bhi theek nahi hai",
            "sleep theek nahi hai",
            "neend nahi aati",
            "neend kharab hai",
            "sleep kharab hai",
            "neend toot",
            "नींद बिगड़ गई है",
            "नींद बिगड़ गई",
            "रात में नींद टूटती रहती है",
            "बार बार नींद टूटती है",
            "नींद बार बार टूटती है",
            "नींद का पैटर्न बदल गया",
            "नींद काफी देर से आती है",
            "नींद देर से आती है",
            "नींद कम आती है",
            "नींद बहुत कम आती है",
            "नींद कम समय के लिए आती है",
            "नींद काफी कम समय के लिए आती है",
            "देर से सोने जाता हूं",
            "देर से सोने जाती हूं",
            "काफी देर से सोने जाता हूं",
            "काफी देर से सोने जाती हूं",
            "neend ka pattern badal gaya",
            "neend ka pattern change ho gaya",
            "neend kaafi der se aati hai",
            "neend der se aati hai",
            "neend kam aati hai",
            "नींद टूट जाती है",
            "नींद टूट टूट कर आती है",
            "रात में नींद टूट जाती है",
            "रात को 3 बजे आंख खुल जाती है",
            "3 4 बजे के आसपास आंख खुल जाती है",
            "रात के तीन-चार बजे उठ जाता हूँ",
            "तीन-चार बजे उठ जाता हूँ",
            "रात देर तक जागता रहता हूँ",
            "wake up at three or four",
            "wake up at 3",
            "wake up around 3 or 4",
            "wake around 3 or 4",
            "wake around 3 or 4 am",
            "fall asleep late",
            "late soti hoon",
            "late sota hoon",
            "sleep comes late",
            "sleep starts late",
            "sleep has been taking forever",
            "taking forever to fall asleep",
            "takes forever to fall asleep",
            "sone mein dikkat",
            "sleep ulta-pulta ho gaya",
            "sleep 3-4 baje hoti hai",
            "raat der tak jagta rehta",
            "raat mein neend toot jati hai",
            "raat ko 3 baje aankh khul jati hai",
            "3 ya 4 baje aankh khul jaati hai",
            "raat ko bhi formulas spin karte rehte hain",
        ),
        2,
        "sleep trouble",
    ),
    PhraseRule(
        "phq_q4_fatigue",
        "PHQ9",
        (
            "always tired",
            "tired all day",
            "drained all day",
            "feel exhausted all day",
            "exhausted all day",
            "dragging myself through the day",
            "drag through the day",
            "drag through everything",
            "din bhar drained rehti hoon",
            "din bhar drained rehta hoon",
            "drained rehti hoon",
            "drained rehta hoon",
            "next day i drag through everything",
            "body thodi down lag rahi hai",
            "body thodi down lag raha hai",
            "body feels heavy",
            "body heavy lagti hai",
            "body heavy lagta hai",
            "body heavy lag rahi hai",
            "body heavy lag raha hai",
            "day ke end tak body heavy lagti hai",
            "morning mein start lena heavy lagta hai",
            "everything feels harder to start",
            "harder to start",
            "uthne ka mann nahi karta",
            "शरीर टूटा सा लगता है",
            "सुबह उठकर शरीर टूटा सा लगता है",
            "सुबह शुरू होने में बहुत समय लगता है",
            "सुबह उठकर भी थकान रहती है",
            "उठकर भी थकान रहती है",
            "mind is slow to get going",
            "mind slow to get going",
            "mind is slow to get going again",
            "mind slow start hota hai",
            "mind slow start hota",
            "pura system drag karta hai",
            "pura system drag karti hai",
            "system drag karta hai",
            "system drag karti hai",
            "takes extra effort to get moving",
            "extra effort to get moving",
            "slow ho gaya hoon",
            "slow ho gayi hoon",
            "no energy",
            "drag through work the next day",
            "drag through the next day",
            "wake up tired",
            "it feels more like low energy",
            "more like low energy than worry",
            "feels more like low energy than worry",
            "next day pura tired feel hota hai",
            "thakawat rehti",
            "hamesha thaka",
            "bilkul energy nahi",
            "आलस रहता है",
            "दिन में आलस रहता है",
            "दिन भर आलस रहता है",
            "सुबह से ही थकान रहती है",
            "दिन भर थकान रहती है",
            "सुबह उठते ही थकान रहती है",
            "साधारण काम भी भारी लगते हैं",
            "सुबह उठकर शरीर भारी लगता है",
            "सुबह उठकर शरीर भारी लगती है",
            "शरीर भारी लगता है",
            "शरीर भारी लगती है",
            "शरीर धीमा पड़ जाता है",
            "andar se pura drained feel hota hai",
            "din bhar thakan rehti hai",
            "din bhar energy low rehti hai",
            "energy low rehti hai",
            "subah uthte hi thakan rehti hai",
            "sadharan kaam bhi bhaari lagte hain",
            "thakan",
            "bas thakan",
            "drag myself",
            "wiped",
            "exhausted feel karta hoon",
            "energy bhi down ho jaati hai",
            "energy bhi down ho jati hai",
            "din ke end tak energy bhi down ho jaati hai",
            "din ke end tak energy bhi down ho jati hai",
            "subah start lene mein kaafi time lagta hai",
            "start lene mein kaafi time lagta hai",
            "ज़्यादा थकान",
            "ज्यादा थकान",
            "thakan zyada lagti hai",
            "body feels slow by evening",
            "body feels slow",
            "body slow ho jati hai",
            "body slow ho jaati hai",
        ),
        2,
        "fatigue",
    ),
    PhraseRule(
        "phq_q5_appetite",
        "PHQ9",
        (
            "not eating much",
            "eating too much",
            "appetite is off",
            "skip meals",
            "skipping meals",
            "skip lunch without noticing",
            "bhook nahi lagti",
            "zyada khana",
            "भूख कम हो गई है",
            "भूख पहले जैसी नहीं है",
            "भूख भी पहले जैसी नहीं है",
            "बस समय देखकर कुछ खा लेती हूँ",
            "khane ka mann nahi",
            "still have not eaten properly",
            "whatever is quickest",
            "bhook bhi pehle jaisi nahi hai",
            "samay dekhkar kuch kha leti hoon",
            "pet mein kuch dalne ka mann nahi karta",
            "khana random ho gaya hai",
            "my appetite is off",
            "lunch just slips",
            "lunch slips",
            "lunch miss ho jata hai",
            "meals delay ho jate hain",
            "meals delay ho jaate hain",
            "meals bhi slip ho jaate hain",
            "meals bhi slip ho jate hain",
            "meals get irregular",
            "meals get irregular too",
            "meals get irregular because i keep delaying them",
            "meals get delayed",
            "bhook thodi gadbad hai",
            "bhook bhi thodi gadbad hai",
            "भूख थोड़ी गड़बड़ है",
            "भूख भी थोड़ी गड़बड़ है",
            "lose track of hunger",
            "lose track of hunger cues",
            "hunger cues feel off",
            "delaying meals",
            "appetite bhi down ho jaati hai",
            "appetite bhi down ho jati hai",
            "bhook bhi kam ho jaati hai",
            "भूख भी कम हो जाती है",
            "खाना छूट जाता है",
            "कई बार खाना छूट जाता है",
            "खाना छोड़ देता हूं",
            "खाना छोड़ देती हूं",
            "भूख का ध्यान नहीं रहता",
            "भूख का ध्यान ही नहीं रहता",
            "दोपहर का खाना छूट जाता है",
            "दोपहर का खाना छूट जाता",
            "dopahar ka khana chhut jata hai",
            "dopahar ka khana chhut jata",
            "eat because i have to",
            "skip meals without noticing",
            "meals skip ho jate hain",
            "meals skip ho jaate hain",
            "bhook pe dhyan nahi rehta",
            "bhook ka dhyan nahi rehta",
            "bhook ka dhyan hi nahi rehta",
        ),
        2,
        "appetite change",
    ),
    PhraseRule(
        "phq_q6_worthlessness",
        "PHQ9",
        (
            "feel like a burden",
            "feel useless",
            "feel guilty",
            "waste everyone's time",
            "wasting everyone's time",
            "disappointing people",
            "it's my fault",
            "main bojh hoon",
            "khud ko bekaar lagta",
            "sab meri galti",
            "मैं इतनी कमजोर क्यों पड़ रही हूँ",
            "मैं अच्छी माँ नहीं हूँ",
            "मुझसे बेहतर संभाल लेते",
            "अगर मैं थोड़ी और संभली हुई होती",
            "मैं कुछ न कुछ गलत कर दूँगी",
            "better off without me around",
            "wasting everyone's time",
            "never cut out for this",
            "main itni kamzor kyon pad rahi hoon",
            "achhi maa nahi hoon",
            "mujhse behtar sambhal lete",
            "utna capable hoon hi nahi",
            "letting people down",
            "feel like i am letting people down",
            "harsh on myself",
            "hard on myself",
            "harder on myself",
            "frustrated with myself",
            "frustration with myself",
            "khud par frustration hoti hai",
            "khud par frustrated feel hota hai",
            "self talk harsh",
            "self-talk harsh",
            "blame myself",
            "everyone else is handling basic life better than i am",
            "बाकी लोग सामान्य चीज़ें मुझसे बेहतर संभाल रहे हैं",
            "बाकी लोग सामान्य चीजें मुझसे बेहतर संभाल रहे हैं",
            "बाकी लोग मुझसे बेहतर संभाल रहे हैं",
            "अपने आप पर गुस्सा आता है",
            "खुद पर गुस्सा आता है",
            "मैं कुछ कर क्यों नहीं पा रहा",
            "मैं कुछ कर क्यों नहीं पा रही",
            "खुद को बहुत कोसता हूँ",
            "खुद को कोसता हूँ",
            "लगता है मैं सब पर बोझ बन रहा हूँ",
            "सब पर बोझ बन रहा हूँ",
            "लगता है मैं सबके लिए बोझ बन रहा हूँ",
            "मैं सबके लिए बोझ बन रहा हूँ",
            "khud ko bahut koshta hoon",
            "khud ko koshta hoon",
            "lagta hai main sab par bojh ban raha hoon",
            "kabhi lagta hai main sabke liye burden ban raha hoon",
            "main sabke liye burden ban raha hoon",
            "main sabke liye burden ban rahi hoon",
            "burden jaisa feel hota hai",
            "kyun nahi kar pa raha",
            "kyun nahi kar pa rahi",
            "judge myself",
            "judging myself",
            "khud ko judge kar raha hoon",
            "khud ko judge kar rahi hoon",
            "अपने ऊपर भी निराशा होती है",
            "अपने ऊपर निराशा होती है",
            "अपने ऊपर झुंझलाहट होती है",
            "अपने ऊपर झुंझलाहट होने लगती है",
            "tiny tasks feel bigger than they should",
        ),
        3,
        "worthlessness",
    ),
    PhraseRule(
        "phq_q7_concentration",
        "PHQ9",
        (
            "can't focus",
            "harder to focus in class",
            "nothing sticks",
            "mind keeps drifting",
            "focus slips",
            "focus toot jata hai",
            "focus toot jaata hai",
            "focus bhi toot jata hai",
            "focus bhi toot jaata hai",
            "focus टूट जाता है",
            "dhyan nahi lagta",
            "dhyan bhi kam lagta hai",
            "focus nahi hota",
            "focus weak ho gaya hai",
            "मन किसी चीज़ में टिकता नहीं",
            "ध्यान टिकता नहीं",
            "ध्यान भी टिकता नहीं",
            "ध्यान भी नहीं टिकता",
            "काम पर ध्यान नहीं टिकता",
            "काम पर ध्यान टूटता है",
            "काम पर ध्यान टूट जाता है",
            "ध्यान टूट जाता है",
            "ध्यान टूटने लगता है",
            "दिमाग नहीं टिकता",
            "क्लास की रिकॉर्डिंग खोलता हूँ पर दिमाग नहीं टिकता",
            "dimag tikta nahi",
            "same paragraph",
            "keep staring at the same screen",
            "staring at the same screen",
            "एक ही चीज़ बार-बार पढ़नी पड़ती है",
            "वही लाइन कई बार पढ़नी पड़ती है",
            "बार-बार पढ़नी पड़ती है",
            "काम या पढ़ाई पर ध्यान भी जल्दी टूट जाता है",
            "ध्यान जल्दी टूट जाता है",
            "stare at the same analysis window",
            "read the same paragraph three times",
            "rereading the same paragraph",
            "same paragraph three times",
            "same line do-teen baar padhni padti hai",
            "reread the same line",
            "reread the same line and still zone out",
            "zone out",
            "same line dobara padhni padti hai",
            "ek hi line dobara padhni padti hai",
            "same line baar baar padhni padti hai",
            "same line par atak jata hai",
            "same line par atak jaata hai",
            "same line par atak jati hai",
            "same line par atak jaati hai",
            "focus same line par atak jata hai",
            "small tasks take forever",
            "small tasks slow lagte hain",
            "long runway before i can start",
            "push maangte hain",
            "dhyan baar baar toot ta hai",
            "ध्यान बार-बार टूटता है",
            "page kholo to mind jump karta rehta hai",
            "class ki recording kholta hoon par dimaag nahi tikta",
            "get nowhere",
        ),
        2,
        "concentration trouble",
    ),
    PhraseRule(
        "phq_q8_psychomotor",
        "PHQ9",
        (
            "moving slowly",
            "talking slowly",
            "pace feels slowed",
            "pace feeling slowed",
            "whole body feels dragged",
            "body feels dragged",
            "body drags through the day",
            "moves feel slowed",
            "so restless i pace",
            "pace around",
            "bahut bechain ho jata",
            "ek jagah tik nahi pata",
            "small tasks take forever",
            "small tasks slow lagte hain",
            "छोटे काम भी लंबे लगते हैं",
            "छोटे काम भी बहुत लंबे लगते हैं",
            "पूरा शरीर घिसटता हुआ लगता है",
            "शरीर घिसटता हुआ लगता है",
            "शरीर भी धीमा पड़ जाता है",
            "धीमा पड़ जाता है",
            "धीमा पड़ जाती है",
            "chhote kaam bhi lambe lagte hain",
            "ghisatta hua lagta hai",
            "ghisatta hua lagti hai",
            "हाथ काँपने लगते हैं",
            "रफ्तार धीमी लगती है",
            "haath kaampne lagte hain",
            "idhar-udhar chakkar lagata rehta hoon",
            "body feels slow by evening",
            "body slow ho jati hai",
            "body slow ho jaati hai",
        ),
        2,
        "psychomotor change",
    ),
    PhraseRule(
        "phq_q9_self_harm",
        "PHQ9",
        (
            "don't want to live",
            "want to disappear",
            "hurt myself",
            "khud ko hurt karne ka plan",
            "khud ko nuksan pahunchane ka man",
            "mar jana chahta",
            "khatam kar doon",
            "सब खत्म कर दूँ",
            "कहीं निकल जाऊँ",
            "सब से गायब हो जाएँ",
            "खुद को नुकसान पहुंचाने",
            "खुद को hurt करने",
            "दुकान की दवाइयाँ एक साथ खा लूँ",
            "jeene ka mann nahi",
            "gayab ho jaun",
            "sab khatam kar doon",
            "dawaiyan ek saath kha loon",
            "disappear karne ka thought",
            "if i could just disappear",
            "everyone would have an easier life if i could just disappear",
            "better off without me around",
        ),
        3,
        "self-harm concern",
    ),
    PhraseRule(
        "gad_q1_nervous",
        "GAD7",
        (
            "always on edge",
            "feel anxious",
            "anxiety kaafi zyada",
            "constantly nervous",
            "ghabrahat rehti",
            "bahut tension rehta",
            "छाती में घबराहट रहती है",
            "दिल एकदम तेज चलने लगता है",
            "हाथ काँपने लगते हैं",
            "andar se ghabrahat",
            "andar hi andar ghabrahat",
            "mind overloaded",
            "keyed up",
            "dil ekdam tez chalne lagta hai",
            "haath thande ho jate hain",
            "chest tight lagti hai",
            "my chest and jaw stay tight",
            "chest and jaw stay tight too",
            "sirr bhara-bhara lagta hai",
            "hath kaampne lagte hain",
            "jaw stays tight all day",
            "clenching my hands",
            "drop in my stomach",
            "worry jumps between work mistakes money and what that means for my future",
            "worry jumps between work mistakes money and future",
            "चिंता काम पैसों और भविष्य के बीच घूमती रहती है",
            "चिंता काम, पैसों और भविष्य के बीच घूमती रहती है",
            "worry work mistakes paise aur future ke beech jump karti rehti hai",
        ),
        2,
        "nervousness",
    ),
    PhraseRule(
        "gad_q2_control_worry",
        "GAD7",
        (
            "can't stop worrying",
            "mind won't stop",
            "mind keeps running",
            "mind keeps looping",
            "thoughts keep looping",
            "thoughts rukte nahi",
            "thoughts do not slow down",
            "thoughts to slow down",
            "worry keeps looping",
            "thoughts won't stop",
            "worry doesn't stop",
            "worry comes back",
            "worrying a lot",
            "soch band nahi hoti",
            "fikar rukti nahi",
            "chinta chalti rehti hai",
            "dimaag mein chinta chalti rehti hai",
            "dimaag chalta rehta hai",
            "दिमाग चलता रहता है",
            "दिमाग शांत नहीं होता",
            "हर समय लगता है",
            "सोच रुकती नहीं",
            "दिमाग को शांत करना मुश्किल",
            "soch chalti rehti hai",
            "worry control nahi hota",
            "overthinking start ho jaati hai",
            "future ko lekar overthinking",
            "dimaag bandh nahi hota",
            "dimaag rukta hi nahi",
            "dimaag ko rokne ki koshish",
            "background mein chalta rehta hai",
            "hard to calm down",
            "brain running mode mein rehta hai",
            "page kholo to mind jump karta rehta hai",
            "formulas spin karte rehte hain",
            "replaying work stuff",
            "replay work stuff",
            "work wali soch chalti rehti hai",
            "काम की बातें दिमाग में चलती रहती हैं",
            "kaam ki baatein dimaag mein chalti rehti hain",
            "mind keeps circling old conversations",
            "old conversations replay",
            "पुरानी बातें घुमाता रहता है",
            "hard to quiet my mind",
            "it is hard to quiet my mind",
            "mind ko quiet karna tough hota hai",
            "mind ko quiet karna tough",
        ),
        3,
        "worry control",
    ),
    PhraseRule(
        "gad_q2_control_worry",
        "GAD7",
        (
            "replay whole conversations",
            "head keeps saying",
            "replaying comments from my advisor",
            "brain keeps replaying comments from my advisor",
        ),
        2,
        "persistent worry loops",
    ),
    PhraseRule(
        "gad_q3_excessive_worry",
        "GAD7",
        (
            "worry about everything",
            "keep thinking about every outcome",
            "work and future",
            "work and the future",
            "about work and the future",
            "worry is mostly about work and whether i ll mess up my future",
            "mess up my future",
            "work aur future",
            "future ke around",
            "har chiz ki chinta",
            "har baat ka darr",
            "हर समय लगता है कि",
            "फोन बजता है तो लगता है",
            "कुछ न कुछ गलत कर दूँगी",
            "sab cheezon ki fikar",
            "relationships aur paise dono handle nahi kar pa raha",
            "sab log age nikal jayenge",
            "kuch na kuch galat kar dungi",
            "phir paise maangne wala hoga",
            "whether i will keep my job",
            "future and job",
            "job aur future",
            "job ko lekar worry",
            "future ko lekar worry",
            "future aur job ko lekar",
            "future aur naukri ko lekar",
            "नौकरी और भविष्य को लेकर",
            "भविष्य और नौकरी को लेकर",
            "get written up",
            "cover rent",
            "not be able to cover rent",
            "say the wrong thing",
            "messed up the marriage",
            "how badly i messed up the marriage",
            "checking work stuff",
            "comments from my advisor",
            "work mistakes",
            "money and what that means for my future",
            "work mistakes money and future",
            "काम पैसों और भविष्य",
            "काम पैसों और भविष्य के बीच",
            "काम, पैसों और भविष्य",
            "paise aur future ke beech",
        ),
        2,
        "excessive worry",
    ),
    PhraseRule(
        "gad_q4_trouble_relaxing",
        "GAD7",
        (
            "brain keeps replaying comments from my advisor",
            "replaying comments from my advisor",
        ),
        1,
        "mild trouble relaxing",
    ),
    PhraseRule(
        "gad_q4_trouble_relaxing",
        "GAD7",
        (
            "can't relax",
            "cannot relax",
            "can't switch off",
            "cannot switch off",
            "hard to calm down",
            "can't settle",
            "cannot settle",
            "never feel settled",
            "aaraam nahi milta",
            "relax nahi kar pata",
            "मन शांत नहीं होता",
            "दिमाग शांत नहीं होता",
            "दिमाग को शांत करना मुश्किल",
            "chain nahi milta",
            "man shant nahi hota",
            "mind ko shant karna mushkil",
            "mind ko quiet karna tough hota hai",
            "body relaxed nahi hoti",
            "room band karke baithna padta hai",
            "brain running mode mein rehta hai",
            "can't really switch off",
            "cannot really switch off",
            "replay whole conversations",
            "if i stop i start thinking",
            "hard to sleep because my head keeps saying",
            "hard to quiet my mind",
            "ज़्यादा दिमाग को शांत करना मुश्किल होता है",
            "body side is there",
            "body side is there but smaller",
            "body me tension hoti hai",
            "body mein tension hoti hai",
            "mind side zyada hota hai",
        ),
        2,
        "trouble relaxing",
    ),
    PhraseRule(
        "gad_q5_restlessness",
        "GAD7",
        (
            "can't sit still",
            "keep pacing",
            "restless all evening",
            "bechain rehta",
            "बेचैनी",
            "chain se baith nahi pata",
            "idhar-udhar chakkar lagata rehta hoon",
            "room mein chakkar lagata rehta hoon",
            "feel restless",
            "बेचैनी दोनों",
            "restlessness aur irritability dono badh jaate hain",
            "restlessness aur irritability dono badh jate hain",
        ),
        2,
        "restlessness",
    ),
    PhraseRule(
        "gad_q6_irritability",
        "GAD7",
        (
            "snapping at people",
            "getting irritated easily",
            "choti baat par gussa",
            "jaldi irritate ho jata",
            "चिड़चिड़ापन आ जाता है",
            "छोटी बात पर भी चिड़चिड़ापन आ जाता है",
            "choti si baat pe irritation aa jati hai",
            "andar se irritation itna hota hai",
            "phat padunga",
            "choti baat par bhi chidhchidhapan",
            "snappy",
            "i get snappy",
            "evenings i get snappy",
            "thoda snappy ho jata hoon",
            "thoda snappy ho jati hoon",
            "शाम तक थोड़ा चिड़चिड़ा हो जाता है",
            "snappy for no good reason",
            "snappy even though i know nobody is doing anything wrong",
            "चिड़चिड़ापन दोनों बढ़ जाते हैं",
            "irritability dono badh jaate hain",
        ),
        2,
        "irritability",
    ),
    PhraseRule(
        "gad_q7_afraid",
        "GAD7",
        (
            "something bad will happen",
            "waiting for the worst",
            "lagta hai kuch bura hoga",
            "dar lagta hai sab kharab ho jayega",
            "सब मुझे जज कर रहे हैं",
            "ऐसा सोचकर डर भी लगता है",
            "judge kar rahe hain",
            "still be stuck pretending i know what i am doing",
            "phone bajta hai to lagta hai phir paise maangne wala hoga",
            "not be able to cover rent",
            "sab log age nikal jayenge",
            "what that means for my future",
            "काम पैसों और भविष्य के बीच घूमती रहती है",
            "काम, पैसों और भविष्य के बीच घूमती रहती है",
            "worry work mistakes paise aur future ke beech jump karti rehti hai",
        ),
        1,
        "fear of awful outcome",
    ),
]

RULE_INDEX: DefaultDict[str, List[PhraseRule]] = defaultdict(list)
for rule in RULES:
    RULE_INDEX[rule.item_id].append(rule)

NEGATION_CUES = (
    "not",
    "don't",
    "dont",
    "don t",
    "do not",
    "never",
    "no",
    "can't",
    "cant",
    "can t",
    "cannot",
    "won't",
    "wont",
    "won t",
    "nahi",
    "nahin",
    "nahi hai",
    "bilkul nahi",
)

HIGH_INTENSITY_CUES = (
    "every day",
    "all day",
    "most days",
    "constantly",
    "always",
    "hamesha",
    "roz",
    "lagatar",
    "har din",
    "bahut zyada",
)

LOW_INTENSITY_CUES = (
    "sometimes",
    "once in a while",
    "kabhi kabhi",
    "thoda",
    "thodi si",
)

UNCERTAINTY_CUES = (
    "maybe",
    "i guess",
    "sort of",
    "not sure",
    "shayad",
)


def rules_for_item(item_id: str) -> Iterable[PhraseRule]:
    return RULE_INDEX[item_id]
