from collections import defaultdict
from dataclasses import dataclass
from typing import DefaultDict, Dict, Iterable, List, Tuple


@dataclass(frozen=True)
class PhraseRule:
    item_id: str
    questionnaire: str
    phrases: Tuple[str, ...]
    score_hint: int
    rationale: str


RULES: List[PhraseRule] = [
    PhraseRule(
        "phq_q1_anhedonia",
        "PHQ9",
        (
            "don't enjoy anything",
            "nothing feels enjoyable",
            "less interest in things",
            "interest has gone down",
            "gaane sunne ka mann nahi karta",
            "mann hi nahi karta",
            "man nahi karta",
            "mann nahi lagta",
            "man nahi lagta",
            "kuch accha nahi lagta",
            "मन नहीं करता",
            "मन ही नहीं करता",
            "किसी काम में मन नहीं लगता",
            "काम में मन नहीं लगता",
            "कुछ अच्छा नहीं लगता",
            "cannot make myself care enough",
            "usually say maybe later",
            "skip basketball",
            "doston se baat karne ka mann nahi karta",
            "friends se baat karne ka mann nahi karta",
            "coding ka mann nahi karta",
            "people se milne ka man nahi karta",
            "लोगों से मिलने का मन नहीं करता",
            "bed se uthne ka mann nahi karta",
            "kaam start karne ka bilkul mann nahi karta",
            "pulling away from people",
            "distance bana leta hoon",
            "interest bhi kam ho gaya hai",
            "रुचि कम हो गई है",
            "ruchi kam ho gayi hai",
            "motivation low rehti hai",
            "motivation stays low",
            "mood crash ho jata",
        ),
        2,
        "reduced interest",
    ),
    PhraseRule(
        "phq_q2_low_mood",
        "PHQ9",
        (
            "feel low",
            "feel down",
            "empty most days",
            "blank feel hota",
            "udaas rehta",
            "bahut udaas",
            "khali khali lagta",
            "अंदर बहुत रोना आता है",
            "बहुत रोना आता है",
            "वॉशरूम में बैठकर रोता हूँ",
            "मन भारी लगता है",
            "feel flat most of the day",
            "drop in my stomach",
            "andar bahut rona aata",
            "pura mood crash ho jata",
            "washroom mein baithkar rota",
        ),
        2,
        "low mood",
    ),
    PhraseRule(
        "phq_q3_sleep",
        "PHQ9",
        (
            "can't sleep",
            "sleeping badly",
            "sleep is bad",
            "sleep is off",
            "sleep keeps breaking",
            "sleep keeps getting interrupted",
            "sleep schedule is messed up",
            "keep waking up",
            "sleep break hoti",
            "sleep break hoti rehti",
            "neend nahi aati",
            "neend kharab hai",
            "sleep kharab hai",
            "neend toot",
            "बार बार नींद टूटती है",
            "नींद बार बार टूटती है",
            "नींद टूट जाती है",
            "नींद टूट टूट कर आती है",
            "रात में नींद टूट जाती है",
            "रात को 3 बजे आंख खुल जाती है",
            "रात देर तक जागता रहता हूँ",
            "wake up at three or four",
            "wake up at 3",
            "wake up around 3 or 4",
            "fall asleep late",
            "sone mein dikkat",
            "sleep ulta-pulta ho gaya",
            "sleep 3-4 baje hoti hai",
            "raat der tak jagta rehta",
            "raat mein neend toot jati hai",
            "raat ko 3 baje aankh khul jati hai",
            "raat ko bhi formulas spin karte rehte hain",
        ),
        2,
        "sleep trouble",
    ),
    PhraseRule(
        "phq_q4_fatigue",
        "PHQ9",
        (
            "always tired",
            "tired all day",
            "drained all day",
            "feel exhausted all day",
            "exhausted all day",
            "no energy",
            "drag through work the next day",
            "drag through the next day",
            "next day pura tired feel hota hai",
            "thakawat rehti",
            "hamesha thaka",
            "bilkul energy nahi",
            "आलस रहता है",
            "दिन भर आलस रहता है",
            "सुबह से ही थकान रहती है",
            "दिन भर थकान रहती है",
            "सुबह उठते ही थकान रहती है",
            "साधारण काम भी भारी लगते हैं",
            "andar se pura drained feel hota hai",
            "din bhar thakan rehti hai",
            "subah uthte hi thakan rehti hai",
            "sadharan kaam bhi bhaari lagte hain",
            "drag myself",
            "wiped",
            "exhausted feel karta hoon",
        ),
        2,
        "fatigue",
    ),
    PhraseRule(
        "phq_q5_appetite",
        "PHQ9",
        (
            "not eating much",
            "eating too much",
            "appetite is off",
            "bhook nahi lagti",
            "zyada khana",
            "भूख कम हो गई है",
            "भूख पहले जैसी नहीं है",
            "भूख भी पहले जैसी नहीं है",
            "बस समय देखकर कुछ खा लेती हूँ",
            "khane ka mann nahi",
            "still have not eaten properly",
            "whatever is quickest",
            "bhook bhi pehle jaisi nahi hai",
            "samay dekhkar kuch kha leti hoon",
            "pet mein kuch dalne ka mann nahi karta",
            "khana random ho gaya hai",
        ),
        2,
        "appetite change",
    ),
    PhraseRule(
        "phq_q6_worthlessness",
        "PHQ9",
        (
            "feel like a burden",
            "feel useless",
            "feel guilty",
            "disappointing people",
            "it's my fault",
            "main bojh hoon",
            "khud ko bekaar lagta",
            "sab meri galti",
            "मैं इतनी कमजोर क्यों पड़ रही हूँ",
            "मैं अच्छी माँ नहीं हूँ",
            "मुझसे बेहतर संभाल लेते",
            "अगर मैं थोड़ी और संभली हुई होती",
            "मैं कुछ न कुछ गलत कर दूँगी",
            "better off without me around",
            "wasting everyone's time",
            "never cut out for this",
            "main itni kamzor kyon pad rahi hoon",
            "achhi maa nahi hoon",
            "mujhse behtar sambhal lete",
            "utna capable hoon hi nahi",
        ),
        3,
        "worthlessness",
    ),
    PhraseRule(
        "phq_q7_concentration",
        "PHQ9",
        (
            "can't focus",
            "harder to focus in class",
            "nothing sticks",
            "mind keeps drifting",
            "dhyan nahi lagta",
            "dhyan bhi kam lagta hai",
            "focus nahi hota",
            "focus weak ho gaya hai",
            "मन किसी चीज़ में टिकता नहीं",
            "दिमाग नहीं टिकता",
            "क्लास की रिकॉर्डिंग खोलता हूँ पर दिमाग नहीं टिकता",
            "dimag tikta nahi",
            "stare at the same analysis window",
            "read the same paragraph three times",
            "same line do-teen baar padhni padti hai",
            "page kholo to mind jump karta rehta hai",
            "class ki recording kholta hoon par dimaag nahi tikta",
            "get nowhere",
        ),
        2,
        "concentration trouble",
    ),
    PhraseRule(
        "phq_q8_psychomotor",
        "PHQ9",
        (
            "moving slowly",
            "talking slowly",
            "so restless i pace",
            "bahut bechain ho jata",
            "ek jagah tik nahi pata",
            "हाथ काँपने लगते हैं",
            "haath kaampne lagte hain",
            "idhar-udhar chakkar lagata rehta hoon",
        ),
        1,
        "psychomotor change",
    ),
    PhraseRule(
        "phq_q9_self_harm",
        "PHQ9",
        (
            "don't want to live",
            "want to disappear",
            "hurt myself",
            "mar jana chahta",
            "khatam kar doon",
            "सब खत्म कर दूँ",
            "कहीं निकल जाऊँ",
            "सब से गायब हो जाएँ",
            "दुकान की दवाइयाँ एक साथ खा लूँ",
            "jeene ka mann nahi",
            "gayab ho jaun",
            "sab khatam kar doon",
            "dawaiyan ek saath kha loon",
            "disappear karne ka thought",
            "if i could just disappear",
            "everyone would have an easier life if i could just disappear",
            "better off without me around",
        ),
        3,
        "self-harm concern",
    ),
    PhraseRule(
        "gad_q1_nervous",
        "GAD7",
        (
            "always on edge",
            "feel anxious",
            "anxiety kaafi zyada",
            "constantly nervous",
            "ghabrahat rehti",
            "bahut tension rehta",
            "छाती में घबराहट रहती है",
            "दिल एकदम तेज चलने लगता है",
            "हाथ काँपने लगते हैं",
            "andar se ghabrahat",
            "dil ekdam tez chalne lagta hai",
            "haath thande ho jate hain",
            "chest tight lagti hai",
            "sirr bhara-bhara lagta hai",
            "hath kaampne lagte hain",
            "jaw stays tight all day",
            "clenching my hands",
            "drop in my stomach",
        ),
        2,
        "nervousness",
    ),
    PhraseRule(
        "gad_q2_control_worry",
        "GAD7",
        (
            "can't stop worrying",
            "mind won't stop",
            "mind keeps running",
            "mind keeps looping",
            "thoughts keep looping",
            "worry keeps looping",
            "thoughts won't stop",
            "worry doesn't stop",
            "worry comes back",
            "worrying a lot",
            "soch band nahi hoti",
            "fikar rukti nahi",
            "chinta chalti rehti hai",
            "dimaag mein chinta chalti rehti hai",
            "dimaag chalta rehta hai",
            "दिमाग चलता रहता है",
            "हर समय लगता है",
            "सोच रुकती नहीं",
            "दिमाग को शांत करना मुश्किल",
            "soch chalti rehti hai",
            "worry control nahi hota",
            "overthinking start ho jaati hai",
            "future ko lekar overthinking",
            "dimaag bandh nahi hota",
            "dimaag rukta hi nahi",
            "dimaag ko rokne ki koshish",
            "background mein chalta rehta hai",
            "hard to calm down",
            "brain running mode mein rehta hai",
            "page kholo to mind jump karta rehta hai",
            "formulas spin karte rehte hain",
        ),
        3,
        "worry control",
    ),
    PhraseRule(
        "gad_q2_control_worry",
        "GAD7",
        (
            "replay whole conversations",
            "head keeps saying",
            "replaying comments from my advisor",
            "brain keeps replaying comments from my advisor",
        ),
        2,
        "persistent worry loops",
    ),
    PhraseRule(
        "gad_q3_excessive_worry",
        "GAD7",
        (
            "worry about everything",
            "keep thinking about every outcome",
            "har chiz ki chinta",
            "har baat ka darr",
            "हर समय लगता है कि",
            "फोन बजता है तो लगता है",
            "कुछ न कुछ गलत कर दूँगी",
            "sab cheezon ki fikar",
            "relationships aur paise dono handle nahi kar pa raha",
            "sab log age nikal jayenge",
            "kuch na kuch galat kar dungi",
            "phir paise maangne wala hoga",
            "whether i will keep my job",
            "future and job",
            "job aur future",
            "job ko lekar worry",
            "future ko lekar worry",
            "future aur job ko lekar",
            "future aur naukri ko lekar",
            "भविष्य और नौकरी को लेकर",
            "get written up",
            "cover rent",
            "not be able to cover rent",
            "say the wrong thing",
            "messed up the marriage",
            "how badly i messed up the marriage",
            "checking work stuff",
            "comments from my advisor",
        ),
        2,
        "excessive worry",
    ),
    PhraseRule(
        "gad_q4_trouble_relaxing",
        "GAD7",
        (
            "brain keeps replaying comments from my advisor",
            "replaying comments from my advisor",
        ),
        1,
        "mild trouble relaxing",
    ),
    PhraseRule(
        "gad_q4_trouble_relaxing",
        "GAD7",
        (
            "can't relax",
            "cannot relax",
            "can't switch off",
            "cannot switch off",
            "hard to calm down",
            "can't settle",
            "cannot settle",
            "never feel settled",
            "aaraam nahi milta",
            "relax nahi kar pata",
            "मन शांत नहीं होता",
            "दिमाग को शांत करना मुश्किल",
            "chain nahi milta",
            "man shant nahi hota",
            "mind ko shant karna mushkil",
            "body relaxed nahi hoti",
            "room band karke baithna padta hai",
            "brain running mode mein rehta hai",
            "can't really switch off",
            "cannot really switch off",
            "replay whole conversations",
            "if i stop i start thinking",
            "hard to sleep because my head keeps saying",
        ),
        2,
        "trouble relaxing",
    ),
    PhraseRule(
        "gad_q5_restlessness",
        "GAD7",
        (
            "can't sit still",
            "keep pacing",
            "restless all evening",
            "bechain rehta",
            "chain se baith nahi pata",
            "idhar-udhar chakkar lagata rehta hoon",
            "room mein chakkar lagata rehta hoon",
        ),
        2,
        "restlessness",
    ),
    PhraseRule(
        "gad_q6_irritability",
        "GAD7",
        (
            "snapping at people",
            "getting irritated easily",
            "choti baat par gussa",
            "jaldi irritate ho jata",
            "चिड़चिड़ापन आ जाता है",
            "छोटी बात पर भी चिड़चिड़ापन आ जाता है",
            "choti si baat pe irritation aa jati hai",
            "andar se irritation itna hota hai",
            "phat padunga",
            "choti baat par bhi chidhchidhapan",
            "snappy for no good reason",
        ),
        1,
        "irritability",
    ),
    PhraseRule(
        "gad_q7_afraid",
        "GAD7",
        (
            "something bad will happen",
            "waiting for the worst",
            "lagta hai kuch bura hoga",
            "dar lagta hai sab kharab ho jayega",
            "सब मुझे जज कर रहे हैं",
            "ऐसा सोचकर डर भी लगता है",
            "judge kar rahe hain",
            "still be stuck pretending i know what i am doing",
            "phone bajta hai to lagta hai phir paise maangne wala hoga",
            "not be able to cover rent",
            "sab log age nikal jayenge",
        ),
        2,
        "fear of awful outcome",
    ),
]

RULE_INDEX: DefaultDict[str, List[PhraseRule]] = defaultdict(list)
for rule in RULES:
    RULE_INDEX[rule.item_id].append(rule)

NEGATION_CUES = (
    "not",
    "don't",
    "dont",
    "don t",
    "do not",
    "never",
    "no",
    "can't",
    "cant",
    "can t",
    "cannot",
    "won't",
    "wont",
    "won t",
    "nahi",
    "nahin",
    "nahi hai",
    "bilkul nahi",
)

HIGH_INTENSITY_CUES = (
    "every day",
    "all day",
    "most days",
    "constantly",
    "always",
    "hamesha",
    "roz",
    "lagatar",
    "har din",
    "bahut zyada",
)

LOW_INTENSITY_CUES = (
    "sometimes",
    "once in a while",
    "kabhi kabhi",
    "thoda",
    "thodi si",
)

UNCERTAINTY_CUES = (
    "maybe",
    "i guess",
    "sort of",
    "not sure",
    "shayad",
    "lagta hai",
)


def rules_for_item(item_id: str) -> Iterable[PhraseRule]:
    return RULE_INDEX[item_id]
