# Generated by Django 4.2.20 on 2026-03-25 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=40, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], max_length=12)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('generation_source', models.CharField(default='synthetic_profile_guided', max_length=80)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('double_annotated', 'Double annotated'), ('consensus_final', 'Consensus final')], default='draft', max_length=24)),
                ('background_profile', models.JSONField(blank=True, default=dict)),
                ('symptom_profile', models.JSONField(blank=True, default=dict)),
                ('annotator_notes', models.TextField(blank=True)),
                ('confidence_notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['conversation_id'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=40, unique=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], max_length=12)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=120)),
                ('disclosure_style', models.CharField(blank=True, max_length=80)),
                ('background_profile', models.JSONField(blank=True, default=dict)),
                ('symptom_profile', models.JSONField(blank=True, default=dict)),
                ('nuance_tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_id', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=12)),
                ('text', models.TextField()),
                ('language_tag', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='screening.conversation')),
            ],
            options={
                'ordering': ['conversation', 'turn_id'],
                'unique_together': {('conversation', 'turn_id')},
            },
        ),
        migrations.CreateModel(
            name='SafetyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('none', 'None'), ('review', 'Review'), ('urgent', 'Urgent')], default='none', max_length=12)),
                ('cues', models.JSONField(blank=True, default=list)),
                ('action_note', models.TextField(blank=True)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_review', to='screening.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_id', models.CharField(max_length=40)),
                ('questionnaire', models.CharField(max_length=8)),
                ('item_id', models.CharField(max_length=64)),
                ('text_span', models.TextField()),
                ('polarity', models.CharField(max_length=12)),
                ('score_hint', models.PositiveSmallIntegerField()),
                ('annotator', models.CharField(blank=True, max_length=80)),
                ('rationale', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_spans', to='screening.conversation')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_spans', to='screening.turn')),
            ],
            options={
                'ordering': ['conversation', 'turn', 'span_id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='screening.patientprofile'),
        ),
        migrations.CreateModel(
            name='AssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_scores', models.JSONField(blank=True, default=dict)),
                ('phq9_labels', models.JSONField(blank=True, default=dict)),
                ('gad7_labels', models.JSONField(blank=True, default=dict)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('unresolved_items', models.JSONField(blank=True, default=list)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshot', to='screening.conversation')),
            ],
        ),
    ]
