#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import sys


PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.generate_seed_scaleup import build_conversation, build_profile


SEED_DIR = PROJECT_ROOT / "data" / "seed"


def nuance_scenarios() -> list[dict]:
    return [
        {
            "patient_id": "MV-P037",
            "conversation_id": "MV-C154",
            "language": "en",
            "age": 26,
            "occupation": "PhD student",
            "context": "advisor pressure and delayed lab results",
            "living_situation": "shared graduate housing",
            "support_system": "texts an older sister late at night",
            "assistant_turns": [
                "What has been feeling hardest over the last couple of weeks?",
                "When you say you're pushing through, what does that look like day to day?",
                "How are sleep, appetite, and concentration showing up in all this?",
                "When things get especially heavy, what thoughts usually show up about yourself?",
            ],
            "user_turns": [
                "I keep telling people I'm just busy, not depressed or anything, but the truth is I drag myself into the lab and feel flat most of the day.",
                "I still answer emails and show up to meetings, but after that I kind of stare at the same analysis window and get nowhere.",
                "Sleep is messy because my brain keeps replaying comments from my advisor, and some days I realize it is late afternoon and I still have not eaten properly.",
                "Mostly that I am wasting everyone's time and maybe I was never cut out for this in the first place.",
            ],
            "disclosure_style": "guarded_then_admitting",
            "nuance_tags": ["deny_then_admit", "academic pressure", "late appetite recognition"],
            "profile_notes": "Starts by minimizing symptoms before naming flat mood, rumination, and self-blame.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 1,
                "phq_q5_appetite": 1,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "I drag myself into the lab and feel flat most of the day",
                    "score_hint": 2,
                    "rationale": "Clear low mood after an initially guarded opening.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 4,
                    "text_span": "I kind of stare at the same analysis window and get nowhere",
                    "score_hint": 2,
                    "rationale": "Direct concentration difficulty tied to academic work.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "Sleep is messy because my brain keeps replaying comments",
                    "score_hint": 2,
                    "rationale": "Rumination disrupting sleep onset and continuity.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "late afternoon and I still have not eaten properly",
                    "score_hint": 1,
                    "rationale": "Reduced or irregular eating during stress.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 8,
                    "text_span": "I am wasting everyone's time",
                    "score_hint": 2,
                    "rationale": "Strong self-critical thinking.",
                },
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 6,
                    "text_span": "my brain keeps replaying comments from my advisor",
                    "score_hint": 2,
                    "rationale": "Persistent worry that is hard to turn off.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Useful guarded case: depression is initially denied, then indirectly disclosed.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q6_worthlessness", "phq_q7_concentration"],
                "low": ["phq_q4_fatigue", "gad_q4_trouble_relaxing"],
            },
            "meta": {
                "guardedness": "high_at_opening",
                "temporal_clarity": "mixed",
                "contradiction_pattern": "minimize_then_admit",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P038",
            "conversation_id": "MV-C155",
            "language": "en",
            "age": 39,
            "occupation": "delivery supervisor",
            "context": "recent separation and alternating weekends with children",
            "living_situation": "rented basement apartment",
            "support_system": "talks to his mother occasionally",
            "assistant_turns": [
                "What tends to hit you hardest on the days that feel worst?",
                "Does the heaviness look more like sadness, worry, or trying to keep busy so you do not feel it?",
                "What happens in the evenings after your kids go back to their mother?",
                "When it gets that low, have you had thoughts about disappearing or not wanting to be here?",
            ],
            "user_turns": [
                "When the kids are with me I can fake being normal, but when they leave the place goes quiet and I feel this drop in my stomach.",
                "I keep cleaning or checking work stuff so I do not sit still, because if I stop I start thinking about how badly I messed up the marriage.",
                "I pace around, maybe pour a drink, and it gets hard to sleep because my head keeps saying they would probably be better off without me around so much.",
                "I am not making a plan or anything, but yes, sometimes it feels like everyone would have an easier life if I could just disappear for a while.",
            ],
            "disclosure_style": "functional_then_passive_risk",
            "nuance_tags": ["post-separation loneliness", "keep-busy coping", "passive disappearance language"],
            "profile_notes": "A realistic passive-risk case where disclosure comes only after repeated functional framing.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q6_worthlessness": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "I feel this drop in my stomach",
                    "score_hint": 2,
                    "rationale": "Marked drop in mood when alone.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "how badly I messed up the marriage",
                    "score_hint": 2,
                    "rationale": "Persistent self-blame.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 4,
                    "text_span": "I keep cleaning or checking work stuff so I do not sit still",
                    "score_hint": 2,
                    "rationale": "Restlessness used to avoid emotional stillness.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "it gets hard to sleep",
                    "score_hint": 2,
                    "rationale": "Sleep disruption tied to rumination.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 8,
                    "text_span": "everyone would have an easier life if I could just disappear",
                    "score_hint": 1,
                    "rationale": "Passive disappearance language without a stated plan.",
                },
            ],
            "safety": {
                "level": "review",
                "cues": ["passive_disappearance", "family_better_without_me"],
                "action_note": "Escalate for human review because passive self-harm language is present.",
            },
            "annotator_notes": "Passive-risk disclosure appears late and should not be missed just because he says there is no plan.",
            "confidence": {
                "high": ["phq_q9_self_harm", "phq_q6_worthlessness", "phq_q3_sleep"],
                "low": ["gad_q1_nervous"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "no_plan_but_passive_risk",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P039",
            "conversation_id": "MV-C156",
            "language": "en",
            "age": 29,
            "occupation": "customer support associate",
            "context": "back-to-back calls and conflict with team lead",
            "living_situation": "lives with two roommates",
            "support_system": "messages a college friend during breaks",
            "assistant_turns": [
                "What has your body been doing when stress spikes at work?",
                "And emotionally, what changes after those stressful shifts?",
                "How have sleep and focus been affected outside work?",
                "What do you find yourself worrying about most once you get home?",
            ],
            "user_turns": [
                "My jaw stays tight all day and I notice I am clenching my hands before difficult calls even start.",
                "By the time I get home I am snappy for no good reason, then I feel bad because I cannot really switch off.",
                "I fall asleep late because I replay whole conversations, and then the next morning I read the same paragraph three times before it sticks.",
                "Mostly that I am going to say the wrong thing, get written up, and suddenly not be able to cover rent.",
            ],
            "disclosure_style": "somatic_then_emotional",
            "nuance_tags": ["somatic anxiety", "rent threat", "irritability after masking"],
            "profile_notes": "Anxiety shows up first through body tension and later through worry and irritability.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q6_irritability": 2,
                "gad_q7_fear_awful": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "My jaw stays tight all day",
                    "score_hint": 2,
                    "rationale": "Persistent bodily tension from anxiety.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 4,
                    "text_span": "I cannot really switch off",
                    "score_hint": 2,
                    "rationale": "Clear trouble relaxing after work.",
                },
                {
                    "item_id": "gad_q6_irritability",
                    "turn_id": 4,
                    "text_span": "I am snappy for no good reason",
                    "score_hint": 2,
                    "rationale": "Explicit irritability.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "I fall asleep late because I replay whole conversations",
                    "score_hint": 2,
                    "rationale": "Late sleep onset due to rumination.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "I read the same paragraph three times",
                    "score_hint": 2,
                    "rationale": "Concentration impairment in daily reading.",
                },
                {
                    "item_id": "gad_q7_fear_awful",
                    "turn_id": 8,
                    "text_span": "not be able to cover rent",
                    "score_hint": 2,
                    "rationale": "Fear of concrete negative consequences.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Helpful for somatic anxiety language and practical fear framing.",
            "confidence": {
                "high": ["gad_q1_nervous", "gad_q4_trouble_relaxing", "gad_q7_fear_awful"],
                "low": ["phq_q3_sleep"],
            },
            "meta": {
                "guardedness": "low",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "none",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P040",
            "conversation_id": "MV-C157",
            "language": "en",
            "age": 43,
            "occupation": "warehouse picker",
            "context": "overtime shifts after staffing shortage",
            "living_situation": "lives with brother",
            "support_system": "mainly keeps things to himself",
            "assistant_turns": [
                "How have you been holding up lately?",
                "When you say you are managing, what feels different from your usual self?",
                "What is happening with rest, food, or motivation outside work?",
                "Do you notice yourself pulling away from people or activities you normally keep up with?",
            ],
            "user_turns": [
                "I mean, I am fine enough. Work is work. I just come home wiped and do not have much left after that.",
                "I guess I get quieter. My brother asks if I want to watch something and I usually say maybe later, then I just sit in the kitchen a while.",
                "My sleep is off because I crash early, wake up at three or four, and then go back in already drained. Eating is mostly whatever is quickest.",
                "Yeah, I have skipped basketball with the same guys two weekends straight because I cannot make myself care enough to go.",
            ],
            "disclosure_style": "stoic_then_specific",
            "nuance_tags": ["minimizing opener", "social withdrawal", "shift fatigue"],
            "profile_notes": "Starts with a stoic front and then gives enough detail for anhedonia, fatigue, and sleep problems.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 3,
                "phq_q5_appetite": 1,
                "phq_q2_low_mood": 1,
            },
            "gad": {},
            "evidence": [
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "I just come home wiped",
                    "score_hint": 3,
                    "rationale": "Strong fatigue phrasing.",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 4,
                    "text_span": "I just sit in the kitchen a while",
                    "score_hint": 1,
                    "rationale": "Low-energy withdrawal without direct sadness wording.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "wake up at three or four",
                    "score_hint": 2,
                    "rationale": "Early waking and poor rest quality.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "Eating is mostly whatever is quickest",
                    "score_hint": 1,
                    "rationale": "Appetite/meal quality change under fatigue.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 8,
                    "text_span": "I have skipped basketball with the same guys",
                    "score_hint": 2,
                    "rationale": "Loss of interest in a usual activity.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Good stoic example where symptoms only become visible through routine changes.",
            "confidence": {
                "high": ["phq_q4_fatigue", "phq_q1_anhedonia", "phq_q3_sleep"],
                "low": ["phq_q2_low_mood", "phq_q5_appetite"],
            },
            "meta": {
                "guardedness": "high",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "fine_enough_then_specifics",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P041",
            "conversation_id": "MV-C158",
            "language": "hi",
            "age": 33,
            "occupation": "school teacher",
            "context": "mother's illness and school paperwork",
            "living_situation": "parents and younger brother",
            "support_system": "talks to a cousin once or twice a week",
            "assistant_turns": [
                "पिछले दो हफ्तों में सबसे ज्यादा भारी क्या लग रहा है?",
                "जब यह दबाव बढ़ता है, तो शरीर और मन दोनों में क्या बदलाव आते हैं?",
                "नींद, भूख और रोज के कामों पर इसका कितना असर पड़ा है?",
                "क्या अपने बारे में भी कुछ नकारात्मक सोच बार-बार आती है?",
            ],
            "user_turns": [
                "स्कूल का काम और घर की जिम्मेदारी दोनों साथ चल रहे हैं, इसलिए दिन भर जैसे सिर भरा-भरा रहता है और मन किसी चीज़ में टिकता नहीं।",
                "छाती में घबराहट रहती है, छोटी बात पर भी चिड़चिड़ापन आ जाता है, फिर खुद पर ही गुस्सा आता है कि मैं इतनी कमजोर क्यों पड़ रही हूँ।",
                "रात में नींद टूट जाती है और सुबह से ही थकान रहती है। भूख भी पहले जैसी नहीं है, बस समय देखकर कुछ खा लेती हूँ।",
                "हाँ, कई बार लगता है कि अगर मैं थोड़ी और संभली हुई होती तो घर का माहौल इतना बोझिल नहीं होता।",
            ],
            "disclosure_style": "somatic_and_guilt",
            "nuance_tags": ["somatic Hindi anxiety", "caregiver guilt", "indirect low mood"],
            "profile_notes": "A caregiver case where worry and guilt are expressed through physical tension and duty language.",
            "phq": {
                "phq_q2_low_mood": 1,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q6_irritability": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 2,
                    "text_span": "मन किसी चीज़ में टिकता नहीं",
                    "score_hint": 1,
                    "rationale": "Concentration loss phrased indirectly.",
                },
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 4,
                    "text_span": "छाती में घबराहट रहती है",
                    "score_hint": 2,
                    "rationale": "Direct somatic anxiety wording in Hindi.",
                },
                {
                    "item_id": "gad_q6_irritability",
                    "turn_id": 4,
                    "text_span": "छोटी बात पर भी चिड़चिड़ापन आ जाता है",
                    "score_hint": 2,
                    "rationale": "Explicit irritability.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "रात में नींद टूट जाती है",
                    "score_hint": 2,
                    "rationale": "Broken sleep.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 8,
                    "text_span": "मैं इतनी कमजोर क्यों पड़ रही हूँ",
                    "score_hint": 2,
                    "rationale": "Self-blaming interpretation of stress.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Good Hindi example where mood is not named directly but guilt and heaviness are clear.",
            "confidence": {
                "high": ["gad_q1_nervous", "phq_q3_sleep", "phq_q6_worthlessness"],
                "low": ["phq_q2_low_mood", "phq_q5_appetite"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "none",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P042",
            "conversation_id": "MV-C159",
            "language": "hi",
            "age": 21,
            "occupation": "college student",
            "context": "hostel isolation and exam backlog",
            "living_situation": "engineering hostel",
            "support_system": "talks to one school friend by phone",
            "assistant_turns": [
                "इन दिनों सबसे मुश्किल क्या लग रहा है?",
                "जब आप कहते हैं कि सब ठीक है, उसके पीछे असल में क्या चल रहा होता है?",
                "पढ़ाई, नींद और लोगों से मिलने-जुलने पर इसका क्या असर पड़ा है?",
                "कभी ऐसा लगता है कि कहीं दूर चले जाएँ या सब से गायब हो जाएँ?",
            ],
            "user_turns": [
                "मैं दोस्तों से यही बोलता हूँ कि बस थोड़ा स्ट्रेस है, डिप्रेशन वगैरह नहीं है।",
                "लेकिन सच में मैं कई रात वॉशरूम में बैठकर रोता हूँ ताकि रूममेट्स को पता न चले।",
                "क्लास की रिकॉर्डिंग खोलता हूँ पर दिमाग नहीं टिकता, रात देर तक जागता रहता हूँ, और अब लोगों से मिलने का मन भी नहीं करता।",
                "हाँ, कभी-कभी लगता है बस कहीं निकल जाऊँ जहाँ कोई मुझे जानता ही न हो। ऐसा सोचकर डर भी लगता है।",
            ],
            "disclosure_style": "deny_then_reveal",
            "nuance_tags": ["denial opening", "hidden crying", "hostel isolation", "passive escape language"],
            "profile_notes": "Strong deny-then-reveal case with passive escape language in Hindi.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q6_worthlessness": 1,
                "phq_q7_concentration": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q2_control_worry": 1,
                "gad_q3_excessive_worry": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 4,
                    "text_span": "मैं कई रात वॉशरूम में बैठकर रोता हूँ",
                    "score_hint": 2,
                    "rationale": "Clear crying spells hidden from peers.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "दिमाग नहीं टिकता",
                    "score_hint": 2,
                    "rationale": "Direct concentration difficulty.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "रात देर तक जागता रहता हूँ",
                    "score_hint": 2,
                    "rationale": "Delayed sleep with late-night waking.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 6,
                    "text_span": "लोगों से मिलने का मन भी नहीं करता",
                    "score_hint": 2,
                    "rationale": "Social withdrawal and loss of interest.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 8,
                    "text_span": "बस कहीं निकल जाऊँ जहाँ कोई मुझे जानता ही न हो",
                    "score_hint": 1,
                    "rationale": "Passive escape/disappearance language.",
                },
            ],
            "safety": {
                "level": "review",
                "cues": ["hidden_crying", "passive_escape_language"],
                "action_note": "Review for passive disappearance language and significant concealment.",
            },
            "annotator_notes": "Useful for Hindi denial patterns and subtle passive safety language.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q7_concentration", "phq_q9_self_harm"],
                "low": ["gad_q2_control_worry"],
            },
            "meta": {
                "guardedness": "high",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "explicit_denial_then_reveal",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P043",
            "conversation_id": "MV-C160",
            "language": "hi",
            "age": 37,
            "occupation": "medical store cashier",
            "context": "debt pressure and repeated calls from lenders",
            "living_situation": "wife and two children",
            "support_system": "almost none outside immediate family",
            "assistant_turns": [
                "इस समय सबसे ज्यादा डर किस बात का लग रहा है?",
                "जब यह दबाव बढ़ता है तो दिमाग में किस तरह के विचार आते हैं?",
                "नींद, शरीर की ऊर्जा और रोज के कामों पर इसका क्या असर पड़ा है?",
                "मैं सीधा पूछना चाहता हूँ: क्या खुद को नुकसान पहुँचाने के बारे में कोई सोच आई है?",
            ],
            "user_turns": [
                "फोन बजता है तो लगता है फिर पैसे माँगने वाला होगा, और दिल एकदम तेज चलने लगता है।",
                "कभी-कभी इतना फँसा हुआ महसूस होता है कि दिमाग कहता है सब खत्म कर दूँ तो शायद घरवालों को मेरे चक्कर से छुटकारा मिल जाए।",
                "नींद टूट-टूट कर आती है, सुबह उठते ही थकान रहती है, फिर भी दुकान पर जाना पड़ता है।",
                "हाँ, दो बार मैंने सोचा कि दुकान की दवाइयाँ एक साथ खा लूँ, हालांकि अभी तक कुछ किया नहीं है।",
            ],
            "disclosure_style": "direct_after_prompt",
            "nuance_tags": ["debt threat", "family burden logic", "direct self-harm intent"],
            "profile_notes": "Urgent Hindi safety case with burden framing and concrete method ideation.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q6_worthlessness": 2,
                "phq_q9_self_harm": 3,
            },
            "gad": {
                "gad_q1_nervous": 3,
                "gad_q3_excessive_worry": 2,
                "gad_q7_fear_awful": 3,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "दिल एकदम तेज चलने लगता है",
                    "score_hint": 3,
                    "rationale": "Severe anxiety cue tied to debt calls.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "घरवालों को मेरे चक्कर से छुटकारा मिल जाए",
                    "score_hint": 2,
                    "rationale": "Burden framing toward family.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 8,
                    "text_span": "दवाइयाँ एक साथ खा लूँ",
                    "score_hint": 3,
                    "rationale": "Direct self-harm ideation with method.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "नींद टूट-टूट कर आती है",
                    "score_hint": 2,
                    "rationale": "Clear sleep disturbance.",
                },
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 6,
                    "text_span": "सुबह उठते ही थकान रहती है",
                    "score_hint": 2,
                    "rationale": "Persistent fatigue.",
                },
            ],
            "safety": {
                "level": "urgent",
                "cues": ["direct_self_harm_method", "family_burden_rationale"],
                "action_note": "Immediate escalation: direct self-harm ideation with available means.",
            },
            "annotator_notes": "High-risk Hindi case. The direct method mention should force urgent escalation.",
            "confidence": {
                "high": ["phq_q9_self_harm", "gad_q1_nervous", "phq_q6_worthlessness"],
                "low": [],
            },
            "meta": {
                "guardedness": "low_once_prompted",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "none",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P044",
            "conversation_id": "MV-C161",
            "language": "hi",
            "age": 30,
            "occupation": "homemaker",
            "context": "new baby and criticism from relatives",
            "living_situation": "husband, infant, in-laws",
            "support_system": "talks to her mother quietly at night",
            "assistant_turns": [
                "इन दिनों आपको सबसे ज्यादा क्या परेशान कर रहा है?",
                "जब घर वाले कुछ कहते हैं, उसका असर भीतर कैसा होता है?",
                "आराम, खाना और रोजमर्रा के काम कितने मुश्किल हो गए हैं?",
                "क्या कभी ऐसा लगता है कि आप जैसी होनी चाहिए थीं वैसी नहीं बन पा रही हैं?",
            ],
            "user_turns": [
                "बच्चे की देखभाल तो चल रही है, लेकिन हर समय लगता है कि मैं कुछ न कुछ गलत कर दूँगी और सब मुझे जज कर रहे हैं।",
                "बाहर से मैं चुप रहती हूँ, पर अंदर बहुत रोना आता है। कई बार बिना वजह ही हाथ काँपने लगते हैं।",
                "नींद तो बच्चे की वजह से टूटती ही है, लेकिन उसके बाद भी मन शांत नहीं होता। भूख कम हो गई है और साधारण काम भी भारी लगते हैं।",
                "हाँ, अक्सर लगता है मैं अच्छी माँ नहीं हूँ और बाकी सब मुझसे बेहतर संभाल लेते।",
            ],
            "disclosure_style": "quiet_then_overwhelmed",
            "nuance_tags": ["postpartum pressure", "judgment sensitivity", "somatic trembling"],
            "profile_notes": "Important postpartum-flavored case without centering diagnosis labels.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
                "phq_q6_worthlessness": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q7_fear_awful": 1,
            },
            "evidence": [
                {
                    "item_id": "gad_q7_fear_awful",
                    "turn_id": 2,
                    "text_span": "मैं कुछ न कुछ गलत कर दूँगी",
                    "score_hint": 1,
                    "rationale": "Fear of doing something wrong around infant care.",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 4,
                    "text_span": "अंदर बहुत रोना आता है",
                    "score_hint": 2,
                    "rationale": "Strong low mood disclosure.",
                },
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 4,
                    "text_span": "हाथ काँपने लगते हैं",
                    "score_hint": 2,
                    "rationale": "Somatic anxiety cue.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "भूख कम हो गई है",
                    "score_hint": 1,
                    "rationale": "Reduced appetite.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 8,
                    "text_span": "मैं अच्छी माँ नहीं हूँ",
                    "score_hint": 2,
                    "rationale": "Clear worthlessness/guilt statement.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Postpartum-related distress is real here, but safety is not directly elevated in this sample.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q6_worthlessness", "gad_q1_nervous"],
                "low": ["gad_q7_fear_awful"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "mixed",
                "contradiction_pattern": "outwardly_quiet_inwardly_overwhelmed",
                "code_mix_pattern": "none",
            },
        },
        {
            "patient_id": "MV-P045",
            "conversation_id": "MV-C162",
            "language": "hinglish",
            "age": 24,
            "occupation": "startup intern",
            "context": "late-night deadlines and social comparison online",
            "living_situation": "PG near office",
            "support_system": "voice notes to one close friend",
            "assistant_turns": [
                "Pichhle do hafte mein sabse zyada kya off lag raha hai?",
                "Jab tum bolte ho ki you are managing, uske peeche actual scene kya hota hai?",
                "Sleep, appetite aur focus ka pattern kaisa ho gaya hai?",
                "Worry zyada kis cheez ko leke spin karti rehti hai?",
            ],
            "user_turns": [
                "Main sabko bol deta hoon ki bas startup life hai, but honestly raat ko laptop band hone ke baad bhi dimaag bandh nahi hota.",
                "I keep doomscrolling and comparing myself, then next day office mein normal act karta hoon even though andar se pura drained feel hota hai.",
                "Sleep 3-4 baje hoti hai, subah uthke pet mein kuch dalne ka mann nahi karta, aur decks dekhte time same line do-teen baar padhni padti hai.",
                "Mostly yahi ki sab log age nikal jayenge and I will still be stuck pretending I know what I am doing.",
            ],
            "disclosure_style": "performing_okay",
            "nuance_tags": ["hinglish masking", "doomscrolling", "comparison spiral"],
            "profile_notes": "Code-mixed example with online comparison and performative normalcy.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
                "phq_q7_concentration": 2,
                "phq_q6_worthlessness": 1,
            },
            "gad": {
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q7_fear_awful": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 2,
                    "text_span": "dimaag bandh nahi hota",
                    "score_hint": 2,
                    "rationale": "Persistent uncontrollable worry in Hinglish phrasing.",
                },
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 4,
                    "text_span": "andar se pura drained feel hota hai",
                    "score_hint": 2,
                    "rationale": "Clear fatigue after emotional masking.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "Sleep 3-4 baje hoti hai",
                    "score_hint": 2,
                    "rationale": "Delayed sleep in code-mixed wording.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "same line do-teen baar padhni padti hai",
                    "score_hint": 2,
                    "rationale": "Concentration difficulty.",
                },
                {
                    "item_id": "gad_q7_fear_awful",
                    "turn_id": 8,
                    "text_span": "sab log age nikal jayenge",
                    "score_hint": 2,
                    "rationale": "Fear of falling behind and future failure.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Good Hinglish case where distress is hidden behind startup humor and online comparison.",
            "confidence": {
                "high": ["phq_q3_sleep", "phq_q7_concentration", "gad_q2_control_worry"],
                "low": ["phq_q6_worthlessness"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "jokes_then_reveals",
                "code_mix_pattern": "english_dominant_hinglish",
            },
        },
        {
            "patient_id": "MV-P046",
            "conversation_id": "MV-C163",
            "language": "hinglish",
            "age": 27,
            "occupation": "BPO employee",
            "context": "night shift and family pressure to marry",
            "living_situation": "with parents",
            "support_system": "one cousin who knows about the night shifts",
            "assistant_turns": [
                "Aajkal sabse zyada kya chipak ke baitha rehta hai dimaag mein?",
                "Jab ghar wale pressure daalte hain, tum usually kaise react karte ho?",
                "Body aur sleep pe iska kya effect ho raha hai?",
                "Kabhi aisa feel hota hai ki bas switch off ho jao ya gayab ho jao?",
            ],
            "user_turns": [
                "Shift khatam hone ke baad bhi brain running mode mein rehta hai, aur ghar aate hi shaadi wali baat shuru ho jati hai.",
                "Main usually bolta hoon chill hai, but andar se irritation itna hota hai ki room band karke baithna padta hai warna phat padunga.",
                "Sleep ulta-pulta ho gaya hai, chest tight lagti hai, aur off day pe bhi body relaxed nahi hoti.",
                "Haan, kabhi-kabhi lagta hai bas pura phone band karke gayab ho jaun for some time. Plan kuch nahi hai, bas disappear karne ka thought aata hai.",
            ],
            "disclosure_style": "surface_calm_then_escape",
            "nuance_tags": ["night shift hinglish", "marriage pressure", "passive disappearance"],
            "profile_notes": "A useful code-mixed passive-risk case with irritability and family-triggered stress.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q6_irritability": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q6_irritability",
                    "turn_id": 4,
                    "text_span": "andar se irritation itna hota hai",
                    "score_hint": 2,
                    "rationale": "Strong irritability in code-mixed wording.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "Sleep ulta-pulta ho gaya hai",
                    "score_hint": 2,
                    "rationale": "Direct sleep disturbance.",
                },
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 6,
                    "text_span": "chest tight lagti hai",
                    "score_hint": 2,
                    "rationale": "Somatic anxiety cue.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 6,
                    "text_span": "body relaxed nahi hoti",
                    "score_hint": 2,
                    "rationale": "Persistent trouble relaxing.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 8,
                    "text_span": "gayab ho jaun for some time",
                    "score_hint": 1,
                    "rationale": "Passive disappearance language without plan.",
                },
            ],
            "safety": {
                "level": "review",
                "cues": ["hinglish_passive_disappearance", "family_pressure_trigger"],
                "action_note": "Review because passive disappearance language is present in a stressed night-shift context.",
            },
            "annotator_notes": "Important Hinglish sample for passive risk that may be missed if the code mix is normalized away.",
            "confidence": {
                "high": ["phq_q9_self_harm", "gad_q4_trouble_relaxing", "gad_q6_irritability"],
                "low": [],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "chill_hai_then_escape_language",
                "code_mix_pattern": "balanced_hinglish",
            },
        },
        {
            "patient_id": "MV-P047",
            "conversation_id": "MV-C164",
            "language": "hinglish",
            "age": 22,
            "occupation": "CA exam candidate",
            "context": "repeat attempt and family comparisons",
            "living_situation": "with parents",
            "support_system": "talks to a friend from coaching",
            "assistant_turns": [
                "Exam ke around abhi sabse tough part kya lag raha hai?",
                "Tum khud ko generally kaise samjhate ho jab panic aata hai?",
                "Reading, memory aur rest ka pattern kaisa ho gaya hai?",
                "Apne aap ke baare mein inner voice kya bolti rehti hai?",
            ],
            "user_turns": [
                "Main khud ko bolta rehta hoon ki this is normal pressure, but mock test se pehle haath thande ho jate hain aur stomach drop jaisa feel hota hai.",
                "Phir main aur zyada schedule bana leta hoon, which sounds productive, but actual padhai utni hoti nahi jitni plan karta hoon.",
                "Page kholo to mind jump karta rehta hai, raat ko bhi formulas spin karte rehte hain, aur next day choti si baat pe irritation aa jati hai.",
                "Bas yahi ki maybe main utna capable hoon hi nahi jitna sab log sochte the.",
            ],
            "disclosure_style": "self-correcting_and_perfectionistic",
            "nuance_tags": ["performance anxiety", "overplanning", "code-mixed self-doubt"],
            "profile_notes": "A nice self-correcting Hinglish case where productivity language hides worry and concentration problems.",
            "phq": {
                "phq_q3_sleep": 1,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 1,
                "gad_q3_excessive_worry": 2,
                "gad_q6_irritability": 1,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "haath thande ho jate hain",
                    "score_hint": 2,
                    "rationale": "Somatic anxiety before exams.",
                },
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 4,
                    "text_span": "aur zyada schedule bana leta hoon",
                    "score_hint": 1,
                    "rationale": "Overplanning as a partial control strategy.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "mind jump karta rehta hai",
                    "score_hint": 2,
                    "rationale": "Clear concentration instability.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "raat ko bhi formulas spin karte rehte hain",
                    "score_hint": 1,
                    "rationale": "Worry-related sleep disturbance.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 8,
                    "text_span": "maybe main utna capable hoon hi nahi",
                    "score_hint": 2,
                    "rationale": "Direct self-doubt and low self-worth.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Good exam-focused Hinglish example with self-correcting language and performance shame.",
            "confidence": {
                "high": ["phq_q7_concentration", "phq_q6_worthlessness", "gad_q1_nervous"],
                "low": ["phq_q3_sleep", "gad_q2_control_worry"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "normal_pressure_then_panic",
                "code_mix_pattern": "balanced_hinglish",
            },
        },
        {
            "patient_id": "MV-P048",
            "conversation_id": "MV-C165",
            "language": "hinglish",
            "age": 31,
            "occupation": "salon manager",
            "context": "breakup and unstable monthly income",
            "living_situation": "shares flat with cousin",
            "support_system": "cousin plus one coworker",
            "assistant_turns": [
                "Recent days mein sabse zyada kis cheez ne hila diya?",
                "Uske baad routine kaunsi jagah se tootne laga?",
                "Emotionally zyada sadness aa rahi hai, anxiety, ya dono mixed hain?",
                "Jab raat ko akela time milta hai tab dimaag kahan chala jata hai?",
            ],
            "user_turns": [
                "Breakup ke baad se kaam pe toh smile kar leta hoon, but ghar aake pura mood crash ho jata hai.",
                "Clients ke saath theek rehta hoon, lekin off ke din bed se uthne ka mann nahi karta aur khana bhi random ho gaya hai.",
                "Dono mixed hain. Kabhi low feel hota hai, kabhi itni bechaini hoti hai ki room mein idhar-udhar chakkar lagata rehta hoon.",
                "Mostly overthinking hoti hai ki main sab relationships aur paise dono handle nahi kar pa raha. Bas raat lambi lagti hai.",
            ],
            "disclosure_style": "social_mask_then_crash",
            "nuance_tags": ["social masking", "relationship loss", "mixed depression-anxiety"],
            "profile_notes": "A mixed Hinglish case without safety escalation but with strong masking and pacing behavior.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q1_anhedonia": 1,
                "phq_q5_appetite": 1,
                "phq_q3_sleep": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q5_restlessness": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "ghar aake pura mood crash ho jata hai",
                    "score_hint": 2,
                    "rationale": "Clear low mood after social masking.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 4,
                    "text_span": "bed se uthne ka mann nahi karta",
                    "score_hint": 1,
                    "rationale": "Reduced drive on off days.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 4,
                    "text_span": "khana bhi random ho gaya hai",
                    "score_hint": 1,
                    "rationale": "Irregular eating pattern.",
                },
                {
                    "item_id": "gad_q5_restlessness",
                    "turn_id": 6,
                    "text_span": "room mein idhar-udhar chakkar lagata rehta hoon",
                    "score_hint": 2,
                    "rationale": "Restlessness with pacing.",
                },
                {
                    "item_id": "gad_q3_excessive_worry",
                    "turn_id": 8,
                    "text_span": "main sab relationships aur paise dono handle nahi kar pa raha",
                    "score_hint": 2,
                    "rationale": "Broad repetitive worry across domains.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Useful for mixed symptoms and social masking in Hinglish without overt crisis language.",
            "confidence": {
                "high": ["phq_q2_low_mood", "gad_q5_restlessness", "gad_q3_excessive_worry"],
                "low": ["phq_q3_sleep", "phq_q5_appetite"],
            },
            "meta": {
                "guardedness": "moderate",
                "temporal_clarity": "clear_recent",
                "contradiction_pattern": "smile_at_work_then_crash",
                "code_mix_pattern": "hindi_dominant_hinglish",
            },
        },
    ]


def main() -> int:
    profiles = []
    conversations = []
    for index, spec in enumerate(nuance_scenarios(), start=1):
        profile = build_profile(spec)
        profile["notes"] = f"{profile.get('notes', '').strip()} Nuance pack sample.".strip()
        profile["seed_metadata"] = spec.get("meta", {})
        profiles.append(profile)

        conversation = build_conversation(spec, index)
        conversation["generation_source"] = "curated_seed_nuance_pack_v1"
        conversation["background_profile"]["support_system"] = spec["support_system"]
        conversation["conversation_metadata"] = spec.get("meta", {})
        conversations.append(conversation)

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    profiles_path = SEED_DIR / "patient_profiles_nuance_pack.json"
    conversations_path = SEED_DIR / "conversations_nuance_pack.json"
    profiles_path.write_text(json.dumps(profiles, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    conversations_path.write_text(json.dumps(conversations, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(profiles_path)
    print(conversations_path)
    print(f"profiles={len(profiles)} conversations={len(conversations)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
