#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import sys


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SEED_DIR = PROJECT_ROOT / "data" / "seed"

PHQ_IDS = [
    "phq_q1_anhedonia",
    "phq_q2_low_mood",
    "phq_q3_sleep",
    "phq_q4_fatigue",
    "phq_q5_appetite",
    "phq_q6_worthlessness",
    "phq_q7_concentration",
    "phq_q8_psychomotor",
    "phq_q9_self_harm",
]

GAD_IDS = [
    "gad_q1_nervous",
    "gad_q2_control_worry",
    "gad_q3_excessive_worry",
    "gad_q4_trouble_relaxing",
    "gad_q5_restlessness",
    "gad_q6_irritability",
    "gad_q7_afraid",
]


def scaleup_scenarios() -> list[dict]:
    return [
        {
            "patient_id": "MV-P013",
            "conversation_id": "MV-C130",
            "language": "en",
            "age": 31,
            "occupation": "night-shift nurse",
            "context": "rotating shifts and guilt about missed family calls",
            "living_situation": "shared staff housing",
            "support_system": "calls a cousin on weekends",
            "assistant_turns": [
                "Over the last couple of weeks, what has felt the heaviest lately?",
                "Is it mainly the sleep disruption, the worry about mistakes, or both?",
                "When the shift ends, what happens to your energy and focus after you get home?",
            ],
            "user_turns": [
                "Honestly it feels like my body never knows when it is supposed to rest. Even on off days I sleep in broken chunks and go back to work already tired.",
                "Both. I replay whether I missed something on the ward, and my chest stays tight while I check notes again and again.",
                "I can still finish the shift, but when I get home I mostly sit there and stare before doing anything useful.",
            ],
            "disclosure_style": "functional_then_emotional",
            "nuance_tags": ["shift work", "sleep fragmentation", "mistake rumination"],
            "profile_notes": "Talks first about physical exhaustion before naming worry.",
            "phq": {
                "phq_q2_low_mood": 1,
                "phq_q3_sleep": 3,
                "phq_q4_fatigue": 3,
                "phq_q7_concentration": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "I sleep in broken chunks",
                    "score_hint": 3,
                    "rationale": "Clear repeated sleep disruption.",
                },
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "go back to work already tired",
                    "score_hint": 3,
                    "rationale": "Persistent fatigue after rest periods.",
                },
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 4,
                    "text_span": "I replay whether I missed something",
                    "score_hint": 2,
                    "rationale": "Repetitive worry that is hard to stop.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 4,
                    "text_span": "my chest stays tight",
                    "score_hint": 2,
                    "rationale": "Sustained tension and inability to settle.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "sit there and stare",
                    "score_hint": 1,
                    "rationale": "Functional slowing after shifts.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Burnout-style presentation with mixed fatigue and worry.",
            "confidence": {
                "high": ["phq_q3_sleep", "phq_q4_fatigue", "gad_q2_control_worry"],
                "low": ["phq_q2_low_mood", "gad_q7_afraid"],
            },
        },
        {
            "patient_id": "MV-P014",
            "conversation_id": "MV-C131",
            "language": "en",
            "age": 34,
            "occupation": "marketing coordinator",
            "context": "recent layoff and rent pressure",
            "living_situation": "one-bedroom apartment",
            "support_system": "talks to an older brother occasionally",
            "assistant_turns": [
                "What has been weighing on you most over the past couple of weeks?",
                "When that heaviness shows up, does it feel more like low mood, guilt, or fear about money?",
                "How has it been affecting food, energy, and the job-search tasks themselves?",
            ],
            "user_turns": [
                "Since the layoffs I wake up late and still feel like I have no real energy. Even applying to jobs feels pointless half the time.",
                "It is all mixed together. I keep thinking I messed everything up for my family, and rent messages make me panic before I even open them.",
                "Some days I skip lunch and just scroll because focusing on applications feels impossible.",
            ],
            "disclosure_style": "shame_then_detail",
            "nuance_tags": ["financial threat", "guilt", "appetite dip"],
            "profile_notes": "Names guilt and practical fear together rather than separating depression and anxiety.",
            "phq": {
                "phq_q1_anhedonia": 1,
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 1,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "I have no real energy",
                    "score_hint": 2,
                    "rationale": "Low energy named directly.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "applying to jobs feels pointless",
                    "score_hint": 1,
                    "rationale": "Reduced motivation and interest in necessary tasks.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "I messed everything up for my family",
                    "score_hint": 2,
                    "rationale": "Strong self-blame phrasing.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "rent messages make me panic",
                    "score_hint": 2,
                    "rationale": "Threat anticipation tied to finances.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "I skip lunch",
                    "score_hint": 1,
                    "rationale": "Reduced eating during stress.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 6,
                    "text_span": "focusing on applications feels impossible",
                    "score_hint": 2,
                    "rationale": "Marked concentration difficulty.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Unemployment case with clear guilt and avoidance around job tasks.",
            "confidence": {
                "high": ["phq_q6_worthlessness", "phq_q7_concentration", "gad_q7_afraid"],
                "low": ["phq_q3_sleep", "gad_q2_control_worry"],
            },
        },
        {
            "patient_id": "MV-P015",
            "conversation_id": "MV-C132",
            "language": "en",
            "age": 28,
            "occupation": "stay-at-home parent",
            "context": "new infant and broken household routine",
            "living_situation": "small apartment with partner and baby",
            "support_system": "mother visits once a week",
            "assistant_turns": [
                "What has felt hardest to carry lately?",
                "Is it more the tension, the crying spells, or the guilt that hits afterward?",
                "What has changed around rest, food, and basic daily tasks?",
            ],
            "user_turns": [
                "When the baby finally sleeps, I should rest too, but I just lie there tense and waiting for the next cry.",
                "I cry much faster these days and then feel guilty because everyone says I should be grateful.",
                "Food does not interest me much and even simple chores feel heavier than they should.",
            ],
            "disclosure_style": "caregiver_minimizing",
            "nuance_tags": ["postpartum stress", "guilt", "hypervigilance"],
            "profile_notes": "Presents distress through caregiving language rather than symptom terms.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 2,
                "phq_q6_worthlessness": 2,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q2_control_worry": 1,
                "gad_q4_trouble_relaxing": 2,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "I just lie there tense",
                    "score_hint": 2,
                    "rationale": "Difficulty resting even when sleep is available.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 2,
                    "text_span": "waiting for the next cry",
                    "score_hint": 2,
                    "rationale": "Ongoing hyper-alert state.",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 4,
                    "text_span": "I cry much faster these days",
                    "score_hint": 2,
                    "rationale": "Frequent crying and lowered mood.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "feel guilty because everyone says I should be grateful",
                    "score_hint": 2,
                    "rationale": "Guilt and self-criticism.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "Food does not interest me much",
                    "score_hint": 2,
                    "rationale": "Clear appetite reduction.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Caregiving strain case with mixed low mood, guilt, and tension.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q5_appetite", "phq_q6_worthlessness"],
                "low": ["gad_q1_nervous", "gad_q7_afraid"],
            },
        },
        {
            "patient_id": "MV-P016",
            "conversation_id": "MV-C133",
            "language": "en",
            "age": 42,
            "occupation": "family caregiver",
            "context": "managing a parent's medical appointments alone",
            "living_situation": "parents' house",
            "support_system": "one sibling in another state",
            "assistant_turns": [
                "What has been taking the biggest toll on you lately?",
                "When you say you are barely holding it together, what kinds of thoughts show up with that exhaustion?",
                "Have those thoughts stayed at the level of wanting escape, or have they become about hurting yourself?",
            ],
            "user_turns": [
                "Most of my day is medicines, appointments, and pretending I can handle it. By night I feel wrung out and cannot settle at all.",
                "Lately I catch myself thinking maybe everyone would have an easier time if I just vanished for a while, which scares me a bit.",
                "I have not done anything, but the thought comes when I am exhausted and feel like a burden.",
            ],
            "disclosure_style": "guarded_then_passive_safety",
            "nuance_tags": ["caregiver burden", "passive death wish", "sleep strain"],
            "profile_notes": "Needs direct but careful follow-up on passive self-harm language.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 3,
                "phq_q6_worthlessness": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q3_excessive_worry": 1,
                "gad_q4_trouble_relaxing": 2,
                "gad_q6_irritability": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "I feel wrung out",
                    "score_hint": 3,
                    "rationale": "Severe caregiver fatigue.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 2,
                    "text_span": "cannot settle at all",
                    "score_hint": 2,
                    "rationale": "Direct difficulty relaxing.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 4,
                    "text_span": "if I just vanished for a while",
                    "score_hint": 1,
                    "rationale": "Passive disappearance wish requiring review.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 6,
                    "text_span": "feel like a burden",
                    "score_hint": 2,
                    "rationale": "Burden-based self-worth language.",
                },
            ],
            "safety": {"level": "review", "cues": ["passive_disappearance", "burden_language"]},
            "annotator_notes": "Passive safety language with exhaustion, not active intent.",
            "confidence": {
                "high": ["phq_q4_fatigue", "phq_q9_self_harm", "phq_q6_worthlessness"],
                "low": ["gad_q3_excessive_worry", "gad_q6_irritability"],
            },
        },
        {
            "patient_id": "MV-P017",
            "conversation_id": "MV-C134",
            "language": "en",
            "age": 27,
            "occupation": "retail manager",
            "context": "short staffing and angry customer complaints",
            "living_situation": "shared house",
            "support_system": "partner listens after shifts",
            "assistant_turns": [
                "What has your body or mind been doing lately when work gets intense?",
                "Does that unease stop after your shift, or does it keep running in the background?",
                "How has it been affecting sleep, restlessness, or how quickly you get irritated?",
            ],
            "user_turns": [
                "The store is short-staffed and I feel on edge before every shift. My legs keep moving and I snap at tiny things.",
                "It keeps going. Even after work I cannot switch off and I keep imagining customers complaining or the manager calling me back.",
                "Sleep comes late because my mind is still racing through worst-case scenes.",
            ],
            "disclosure_style": "physical_then_future_threat",
            "nuance_tags": ["restlessness", "customer stress", "worst-case thinking"],
            "profile_notes": "Anxiety shows up first as body activation and irritability.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q5_restlessness": 2,
                "gad_q6_irritability": 2,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "I feel on edge",
                    "score_hint": 2,
                    "rationale": "Direct nervousness phrasing.",
                },
                {
                    "item_id": "gad_q5_restlessness",
                    "turn_id": 2,
                    "text_span": "My legs keep moving",
                    "score_hint": 2,
                    "rationale": "Clear restlessness.",
                },
                {
                    "item_id": "gad_q3_excessive_worry",
                    "turn_id": 4,
                    "text_span": "I keep imagining customers complaining",
                    "score_hint": 2,
                    "rationale": "Repeated worry about multiple work outcomes.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "Sleep comes late",
                    "score_hint": 2,
                    "rationale": "Difficulty falling asleep due to racing thoughts.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "High-anxiety retail case with strong physical restlessness.",
            "confidence": {
                "high": ["gad_q1_nervous", "gad_q5_restlessness", "gad_q6_irritability"],
                "low": ["phq_q4_fatigue", "gad_q7_afraid"],
            },
        },
        {
            "patient_id": "MV-P018",
            "conversation_id": "MV-C135",
            "language": "en",
            "age": 30,
            "occupation": "doctoral student",
            "context": "research delays and social withdrawal",
            "living_situation": "campus apartment",
            "support_system": "advisor is aware something is wrong",
            "assistant_turns": [
                "What has changed the most for you over the past couple of weeks?",
                "When you say things feel flat and slow, what thoughts have come with that?",
                "Have those thoughts stayed passive, or have they become more specific about hurting yourself?",
            ],
            "user_turns": [
                "For months I have felt flat even around work I used to care about. I move slowly, miss meetings, and then hate myself for it.",
                "It has gotten to the point where I have thought about not waking up, or stepping into traffic on my way in, just so everything would stop.",
                "I have not acted on it, but the thoughts feel more specific this week and that is why I am talking about it now.",
            ],
            "disclosure_style": "slow_build_to_specific_risk",
            "nuance_tags": ["anhedonia", "psychomotor slowing", "specific self-harm ideation"],
            "profile_notes": "Urgent case with clear escalation from passive to specific thoughts.",
            "phq": {
                "phq_q1_anhedonia": 3,
                "phq_q2_low_mood": 3,
                "phq_q3_sleep": 1,
                "phq_q4_fatigue": 2,
                "phq_q6_worthlessness": 3,
                "phq_q7_concentration": 2,
                "phq_q8_psychomotor": 1,
                "phq_q9_self_harm": 3,
            },
            "gad": {
                "gad_q2_control_worry": 1,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "work I used to care about",
                    "score_hint": 3,
                    "rationale": "Loss of interest in previously meaningful work.",
                },
                {
                    "item_id": "phq_q8_psychomotor",
                    "turn_id": 2,
                    "text_span": "I move slowly",
                    "score_hint": 1,
                    "rationale": "Psychomotor slowing phrase.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 2,
                    "text_span": "hate myself for it",
                    "score_hint": 3,
                    "rationale": "Strong self-loathing.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 4,
                    "text_span": "stepping into traffic on my way in",
                    "score_hint": 3,
                    "rationale": "Specific self-harm thought requiring urgent escalation.",
                },
            ],
            "safety": {"level": "urgent", "cues": ["traffic_method", "specific_not_waking_up_thoughts"]},
            "annotator_notes": "Urgent safety case with specific scenario-based ideation.",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q6_worthlessness", "phq_q9_self_harm"],
                "low": ["gad_q2_control_worry", "phq_q3_sleep"],
            },
        },
        {
            "patient_id": "MV-P019",
            "conversation_id": "MV-C136",
            "language": "en",
            "age": 36,
            "occupation": "restaurant worker",
            "context": "late shifts, remittance pressure, and isolation",
            "living_situation": "shared basement apartment",
            "support_system": "sends voice notes to family abroad",
            "assistant_turns": [
                "What has the last couple of weeks been feeling like for you?",
                "When the day ends, is it sadness, worry about money, or something else that keeps going?",
                "How have sleep and eating been affected when that pressure stays with you?",
            ],
            "user_turns": [
                "I keep telling my family I am managing, but after late shifts I mostly feel empty and too tired to talk.",
                "Money thoughts start the second I lie down, and then I wake up again before sunrise checking the time.",
                "Meals are random now, and I worry that one bad month will ruin everything.",
            ],
            "disclosure_style": "protective_of_family",
            "nuance_tags": ["financial stress", "isolation", "early waking"],
            "profile_notes": "Downplays distress to protect family, then reveals emptiness and money fear.",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q3_excessive_worry": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "I mostly feel empty",
                    "score_hint": 2,
                    "rationale": "Direct emptiness wording.",
                },
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "too tired to talk",
                    "score_hint": 2,
                    "rationale": "Persistent exhaustion after work.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 4,
                    "text_span": "wake up again before sunrise",
                    "score_hint": 2,
                    "rationale": "Repeated early waking.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 6,
                    "text_span": "one bad month will ruin everything",
                    "score_hint": 2,
                    "rationale": "Catastrophic future fear.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Low disclosure style with clear financial-catastrophe worry.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q3_sleep", "gad_q7_afraid"],
                "low": ["phq_q5_appetite", "gad_q1_nervous"],
            },
        },
        {
            "patient_id": "MV-P020",
            "conversation_id": "MV-C137",
            "language": "en",
            "age": 29,
            "occupation": "startup founder",
            "context": "investor uncertainty and nonstop product deadlines",
            "living_situation": "solo apartment",
            "support_system": "one cofounder who knows part of the story",
            "assistant_turns": [
                "What has your head been doing lately when the pressure spikes?",
                "When one thing goes wrong, where does your mind usually go next?",
                "What has this been doing to focus, energy, and interest in the work itself?",
            ],
            "user_turns": [
                "People think I am motivated, but mostly I feel wired and blank at the same time. I jump between tabs and finish very little.",
                "If one investor email is slow, my head goes straight to the company collapsing.",
                "I try to hide it, but I have stopped enjoying even the parts I used to love.",
            ],
            "disclosure_style": "high_functioning_mask",
            "nuance_tags": ["catastrophizing", "concentration", "anhedonia"],
            "profile_notes": "Looks productive from outside but describes blankness and collapse narratives.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 1,
                "phq_q4_fatigue": 1,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 1,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 1,
                "gad_q5_restlessness": 1,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 2,
                    "text_span": "I jump between tabs and finish very little",
                    "score_hint": 2,
                    "rationale": "Difficulty sustaining attention.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "the company collapsing",
                    "score_hint": 2,
                    "rationale": "Rapid catastrophic escalation.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 6,
                    "text_span": "stopped enjoying even the parts I used to love",
                    "score_hint": 2,
                    "rationale": "Reduced interest in previously enjoyable work.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Mixed activation and flattening with strong collapse thinking.",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q7_concentration", "gad_q7_afraid"],
                "low": ["phq_q4_fatigue", "gad_q4_trouble_relaxing"],
            },
        },
        {
            "patient_id": "MV-P021",
            "conversation_id": "MV-C138",
            "language": "hi",
            "age": 24,
            "occupation": "सरकारी परीक्षा अभ्यर्थी",
            "context": "परीक्षा की तैयारी और पारिवारिक उम्मीदें",
            "living_situation": "माता-पिता के साथ",
            "support_system": "एक दोस्त से कभी-कभी बात",
            "assistant_turns": [
                "पिछले दो हफ्तों में सबसे भारी क्या लग रहा है?",
                "ये ज़्यादा घबराहट है, ध्यान टूटना है, या घरवालों को निराश करने का डर?",
                "नींद, पढ़ाई और अपने बारे में जो सोच चलती है, उसमें क्या बदलाव आया है?",
            ],
            "user_turns": [
                "नींद बार-बार टूटती है और सुबह उठते ही दिल घबराने लगता है कि फिर पढ़ाई पीछे रह जाएगी।",
                "किताब खोलता हूँ पर ध्यान टिकता नहीं, बस यही चलता रहता है कि अगर इस बार भी नहीं हुआ तो क्या होगा।",
                "घर वाले कुछ नहीं कहते, फिर भी मुझे लगता है मैं सबको निराश कर रहा हूँ।",
            ],
            "disclosure_style": "performance_pressure",
            "nuance_tags": ["exam stress", "sleep break", "family expectations"],
            "profile_notes": "शुरुआत घबराहट से करता है, बाद में शर्म और निराशा की बात लाता है।",
            "phq": {
                "phq_q2_low_mood": 1,
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 1,
                "phq_q6_worthlessness": 1,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 3,
                "gad_q4_trouble_relaxing": 1,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "नींद बार-बार टूटती है",
                    "score_hint": 2,
                    "rationale": "सीधी नींद टूटने की शिकायत।",
                },
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "दिल घबराने लगता है",
                    "score_hint": 2,
                    "rationale": "घबराहट का स्पष्ट शारीरिक वर्णन।",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 4,
                    "text_span": "ध्यान टिकता नहीं",
                    "score_hint": 2,
                    "rationale": "पढ़ाई के दौरान ध्यान का टूटना।",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "अगर इस बार भी नहीं हुआ तो क्या होगा",
                    "score_hint": 2,
                    "rationale": "असफलता के बारे में भविष्य-भय।",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 6,
                    "text_span": "मैं सबको निराश कर रहा हूँ",
                    "score_hint": 1,
                    "rationale": "खुद को विफल मानने की भावना।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "प्रदर्शन-आधारित चिंता और आत्म-दोष का मिश्रण।",
            "confidence": {
                "high": ["phq_q3_sleep", "phq_q7_concentration", "gad_q3_excessive_worry"],
                "low": ["phq_q2_low_mood", "gad_q4_trouble_relaxing"],
            },
        },
        {
            "patient_id": "MV-P022",
            "conversation_id": "MV-C139",
            "language": "hi",
            "age": 38,
            "occupation": "गृहिणी",
            "context": "घर और बुज़ुर्ग देखभाल की दोहरी जिम्मेदारी",
            "living_situation": "संयुक्त परिवार",
            "support_system": "पड़ोस की एक सहेली",
            "assistant_turns": [
                "इन दिनों सबसे ज़्यादा थकाने वाली बात क्या लग रही है?",
                "ये ज़्यादा उदासी है, अपराधबोध है, या लगातार तनाव बना रहता है?",
                "खाने, रोने, और रोज़मर्रा के कामों पर इसका क्या असर पड़ रहा है?",
            ],
            "user_turns": [
                "पूरा दिन घर और सास की देखभाल में निकल जाता है, लेकिन अब छोटे काम भी बहुत भारी लगते हैं।",
                "बिना वजह रोना आ जाता है और लगता है कि मैं अच्छी बहू या माँ भी नहीं हूँ।",
                "भूख कम हो गई है और रात को शरीर थका होता है, फिर भी दिमाग शांत नहीं होता।",
            ],
            "disclosure_style": "role_based",
            "nuance_tags": ["care burden", "self-blame", "reduced appetite"],
            "profile_notes": "लक्षणों को घर की भूमिका के संदर्भ में बताती है।",
            "phq": {
                "phq_q2_low_mood": 2,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 2,
                "phq_q6_worthlessness": 2,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q2_control_worry": 1,
                "gad_q4_trouble_relaxing": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "छोटे काम भी बहुत भारी लगते हैं",
                    "score_hint": 2,
                    "rationale": "ऊर्जा और कार्य-क्षमता में गिरावट।",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 4,
                    "text_span": "बिना वजह रोना आ जाता है",
                    "score_hint": 2,
                    "rationale": "उदासी का सीधा संकेत।",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "मैं अच्छी बहू या माँ भी नहीं हूँ",
                    "score_hint": 2,
                    "rationale": "भूमिका-आधारित आत्म-आलोचना।",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "भूख कम हो गई है",
                    "score_hint": 2,
                    "rationale": "स्पष्ट भूख में कमी।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "घर की जिम्मेदारियों के बीच अवसाद-नुमा थकान और अपराधबोध।",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q5_appetite", "phq_q6_worthlessness"],
                "low": ["gad_q1_nervous", "gad_q4_trouble_relaxing"],
            },
        },
        {
            "patient_id": "MV-P023",
            "conversation_id": "MV-C140",
            "language": "hi",
            "age": 26,
            "occupation": "डिलिवरी कर्मी",
            "context": "सड़क दुर्घटना के बाद काम पर वापसी",
            "living_situation": "दो दोस्तों के साथ किराये पर",
            "support_system": "छोटा भाई फोन पर",
            "assistant_turns": [
                "पिछले कुछ समय में सबसे परेशान करने वाली चीज़ क्या रही है?",
                "ये डर सड़क पर ही रहता है या घर लौटने के बाद भी बना रहता है?",
                "शरीर, आराम, और बुरा होने के डर पर इसका क्या असर है?",
            ],
            "user_turns": [
                "एक छोटे एक्सीडेंट के बाद से सड़क पर निकलते ही शरीर तन जाता है और हर हॉर्न पर चौंक जाता हूँ।",
                "काम करना पड़ता है, लेकिन मन में चलता रहता है कि फिर कुछ बुरा न हो जाए।",
                "घर आकर भी चक्कर काटता रहता हूँ, बैठकर आराम करना मुश्किल हो गया है।",
            ],
            "disclosure_style": "body_first",
            "nuance_tags": ["accident fear", "hyperarousal", "restlessness"],
            "profile_notes": "घटना के बाद शरीर और भविष्य-भय दोनों बढ़े हैं।",
            "phq": {
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q5_restlessness": 2,
                "gad_q7_afraid": 3,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "शरीर तन जाता है",
                    "score_hint": 2,
                    "rationale": "शारीरिक घबराहट और तनाव।",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "फिर कुछ बुरा न हो जाए",
                    "score_hint": 3,
                    "rationale": "तेज़ भविष्य-आधारित डर।",
                },
                {
                    "item_id": "gad_q5_restlessness",
                    "turn_id": 6,
                    "text_span": "चक्कर काटता रहता हूँ",
                    "score_hint": 2,
                    "rationale": "आराम न कर पाना और बेचैनी।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "दुर्घटना के बाद की चिंता, बेचैनी और सतर्कता।",
            "confidence": {
                "high": ["gad_q1_nervous", "gad_q5_restlessness", "gad_q7_afraid"],
                "low": ["phq_q4_fatigue", "gad_q3_excessive_worry"],
            },
        },
        {
            "patient_id": "MV-P024",
            "conversation_id": "MV-C141",
            "language": "hi",
            "age": 20,
            "occupation": "कॉलेज छात्रा",
            "context": "होस्टल जीवन और सामाजिक अलगाव",
            "living_situation": "महिला छात्रावास",
            "support_system": "एक रूममेट पर थोड़ा भरोसा",
            "assistant_turns": [
                "अभी सबसे ज़्यादा भारी क्या महसूस हो रहा है?",
                "जब आप कहती हैं कि भीतर से खाली लगता है, उस समय और क्या चलता है?",
                "जब 'गायब हो जाने' जैसा ख्याल आता है, क्या वो सिर्फ दूर जाने जैसा लगता है या खुद को नुकसान पहुँचाने जैसा भी?",
            ],
            "user_turns": [
                "कॉलेज में सबके बीच हूँ फिर भी अंदर से काफी खाली-खाली लगता है। पहले जिन चीजों में मज़ा आता था, अब उनमें भी मन नहीं लगता।",
                "कभी-कभी लगता है बस कहीं गायब हो जाऊँ तो आसान होगा, क्योंकि किसी से समझाना भी नहीं पड़ता।",
                "मैंने अपने आप को नुकसान नहीं पहुँचाया है, पर ये सोच आने लगी है तो डर लग रहा है।",
            ],
            "disclosure_style": "socially_present_but_empty",
            "nuance_tags": ["anhedonia", "emptiness", "passive disappearance"],
            "profile_notes": "ऊपरी सामाजिक मौजूदगी के बावजूद भीतर खालीपन और रिव्यू-लेवल सुरक्षा संकेत।",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 2,
                "phq_q6_worthlessness": 1,
                "phq_q7_concentration": 1,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q2_control_worry": 1,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "अंदर से काफी खाली-खाली लगता है",
                    "score_hint": 2,
                    "rationale": "खालीपन और उदासी का वर्णन।",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "जिन चीजों में मज़ा आता था, अब उनमें भी मन नहीं लगता",
                    "score_hint": 2,
                    "rationale": "रुचि में कमी।",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 4,
                    "text_span": "बस कहीं गायब हो जाऊँ",
                    "score_hint": 1,
                    "rationale": "निष्क्रिय सुरक्षा-चिंता वाला कथन।",
                },
            ],
            "safety": {"level": "review", "cues": ["passive_disappearance"]},
            "annotator_notes": "रिव्यू-लेवल सुरक्षा संकेत, सक्रिय योजना नहीं।",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q2_low_mood", "phq_q9_self_harm"],
                "low": ["gad_q1_nervous", "phq_q7_concentration"],
            },
        },
        {
            "patient_id": "MV-P025",
            "conversation_id": "MV-C142",
            "language": "hi",
            "age": 33,
            "occupation": "स्कूल शिक्षिका",
            "context": "नए शहर में तबादला",
            "living_situation": "किराये का कमरा",
            "support_system": "बहन से फोन पर बात",
            "assistant_turns": [
                "इन दिनों सबसे ज़्यादा क्या बदल गया है?",
                "ये ज़्यादा अकेलापन है, उदासी है, या भविष्य की चिंता साथ चलती रहती है?",
                "नींद, भूख और लोगों से बात करने की इच्छा पर इसका क्या असर है?",
            ],
            "user_turns": [
                "नई जगह आने के बाद से रात को नींद नहीं जमती और सुबह उठकर भी मन बुझा-बुझा रहता है।",
                "स्कूल में पढ़ाते समय ठीक रहता है, लेकिन घर लौटते ही लगता है कि किसी से बात करने का मन नहीं है।",
                "भूख भी कम है और छोटी-छोटी बातों पर भविष्य को लेकर चिंता शुरू हो जाती है।",
            ],
            "disclosure_style": "structured_during_work_only",
            "nuance_tags": ["transfer stress", "loneliness", "future worry"],
            "profile_notes": "काम के दौरान कार्यशील, घर लौटते ही लक्षण बढ़ते हैं।",
            "phq": {
                "phq_q1_anhedonia": 1,
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q5_appetite": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q3_excessive_worry": 1,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "रात को नींद नहीं जमती",
                    "score_hint": 2,
                    "rationale": "नींद आने में कठिनाई।",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "मन बुझा-बुझा रहता है",
                    "score_hint": 2,
                    "rationale": "स्पष्ट उदासी।",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 4,
                    "text_span": "किसी से बात करने का मन नहीं है",
                    "score_hint": 1,
                    "rationale": "सामाजिक रुचि में कमी।",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "भूख भी कम है",
                    "score_hint": 1,
                    "rationale": "भूख कम होना।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "तबादले के बाद अकेलापन और हल्की चिंता के साथ उदासी।",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q3_sleep", "phq_q5_appetite"],
                "low": ["gad_q1_nervous", "gad_q7_afraid"],
            },
        },
        {
            "patient_id": "MV-P026",
            "conversation_id": "MV-C143",
            "language": "hi",
            "age": 41,
            "occupation": "दुकानदार",
            "context": "कर्ज और कम होती बिक्री",
            "living_situation": "परिवार के साथ दुकान के ऊपर",
            "support_system": "पत्नी सुनती है लेकिन चिंतित हो जाती है",
            "assistant_turns": [
                "अभी सबसे ज़्यादा दिमाग पर क्या चल रहा है?",
                "जब कर्ज का दबाव आता है, उस समय शरीर और सोच में क्या होता है?",
                "आराम, चिड़चिड़ापन और सबसे बुरा होने का डर किस तरह दिखता है?",
            ],
            "user_turns": [
                "दुकान का कर्ज सिर पर है, इसलिए पूरे दिन सीने में खिंचाव और बेचैनी बनी रहती है।",
                "गिनती करते-करते भी लगता है कुछ बहुत गलत होने वाला है, इसलिए दिमाग बार-बार उसी पर अटक जाता है।",
                "घर वाले कुछ पूछ लें तो मैं जल्दी चिड़चिड़ा हो जाता हूँ और रात को आराम नहीं मिलता।",
            ],
            "disclosure_style": "money_pressure_body_symptoms",
            "nuance_tags": ["debt stress", "physical anxiety", "irritability"],
            "profile_notes": "वित्तीय दबाव शरीर, डर, और चिड़चिड़ेपन के रूप में आता है।",
            "phq": {
                "phq_q3_sleep": 1,
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q6_irritability": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "सीने में खिंचाव और बेचैनी",
                    "score_hint": 2,
                    "rationale": "घबराहट की शारीरिक अनुभूति।",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "कुछ बहुत गलत होने वाला है",
                    "score_hint": 2,
                    "rationale": "बड़ी अनहोनी का डर।",
                },
                {
                    "item_id": "gad_q6_irritability",
                    "turn_id": 6,
                    "text_span": "जल्दी चिड़चिड़ा हो जाता हूँ",
                    "score_hint": 2,
                    "rationale": "स्पष्ट चिड़चिड़ापन।",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 6,
                    "text_span": "रात को आराम नहीं मिलता",
                    "score_hint": 2,
                    "rationale": "आराम न मिलना और तनाव बना रहना।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "उच्च चिंता का मामला, अवसाद संकेत हल्के हैं।",
            "confidence": {
                "high": ["gad_q1_nervous", "gad_q4_trouble_relaxing", "gad_q6_irritability"],
                "low": ["phq_q4_fatigue", "phq_q3_sleep"],
            },
        },
        {
            "patient_id": "MV-P027",
            "conversation_id": "MV-C144",
            "language": "hi",
            "age": 47,
            "occupation": "सिलाई कामगार",
            "context": "पति के निधन के बाद अकेले काम संभालना",
            "living_situation": "बेटी के साथ छोटा घर",
            "support_system": "पास की रिश्तेदार",
            "assistant_turns": [
                "आजकल सबसे ज़्यादा क्या महसूस हो रहा है?",
                "जब आप कहती हैं कि मन नहीं लगता, उस समय अपने बारे में क्या सोच आती है?",
                "खाने, चाल-ढाल, और खालीपन के असर कैसे दिख रहे हैं?",
            ],
            "user_turns": [
                "सिलाई का काम हाथ में रहता है, पर मन जैसे कहीं लगता ही नहीं। दिन भर सुस्ती और खालीपन बना रहता है।",
                "धीरे-धीरे बोलती हूँ, काम में भी देर लगती है, और अक्सर लगता है कि मेरे होने से किसी को खास फर्क नहीं पड़ता।",
                "खाना भी बस मजबूरी में खाती हूँ, क्योंकि इच्छा बहुत कम हो गई है।",
            ],
            "disclosure_style": "slow_grief_like_depression",
            "nuance_tags": ["anhedonia", "emptiness", "psychomotor slowing"],
            "profile_notes": "धीमी गति और अर्थहीनता की भावना प्रमुख है।",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 3,
                "phq_q4_fatigue": 2,
                "phq_q5_appetite": 1,
                "phq_q6_worthlessness": 2,
                "phq_q8_psychomotor": 1,
            },
            "gad": {},
            "evidence": [
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "मन जैसे कहीं लगता ही नहीं",
                    "score_hint": 2,
                    "rationale": "रुचि और संलग्नता में कमी।",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "खालीपन बना रहता है",
                    "score_hint": 3,
                    "rationale": "लगातार खालीपन और उदासी।",
                },
                {
                    "item_id": "phq_q8_psychomotor",
                    "turn_id": 4,
                    "text_span": "धीरे-धीरे बोलती हूँ",
                    "score_hint": 1,
                    "rationale": "धीमी चाल-ढाल/बोलना।",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "मेरे होने से किसी को खास फर्क नहीं पड़ता",
                    "score_hint": 2,
                    "rationale": "स्व-मूल्य में गिरावट।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "अवसाद-प्रधान केस, चिंता सीमित है।",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q6_worthlessness", "phq_q8_psychomotor"],
                "low": ["phq_q5_appetite"],
            },
        },
        {
            "patient_id": "MV-P028",
            "conversation_id": "MV-C145",
            "language": "hi",
            "age": 29,
            "occupation": "कॉल सेंटर कर्मचारी",
            "context": "नाइट शिफ्ट और कॉल क्वालिटी का दबाव",
            "living_situation": "दो सहकर्मियों के साथ फ्लैट",
            "support_system": "माँ से रोज़ थोड़ी बात",
            "assistant_turns": [
                "पिछले कुछ समय से सबसे मुश्किल क्या चल रहा है?",
                "ये ज़्यादा नींद, गलती का डर, या लगातार थकावट के रूप में आता है?",
                "शिफ्ट के बाद शरीर और दिमाग किस तरह प्रतिक्रिया देते हैं?",
            ],
            "user_turns": [
                "नाइट शिफ्ट की वजह से नींद पूरी उलट गई है, और सुबह तक सिर भारी रहता है।",
                "कॉल के बीच ध्यान टूट जाता है, फिर डर लगता है कि गलती हो गई तो नौकरी चली जाएगी।",
                "ऑफ डे पर भी शरीर ढीला रहता है और दिमाग आराम करना भूल गया है।",
            ],
            "disclosure_style": "work_error_anxiety",
            "nuance_tags": ["night shift", "job loss fear", "focus drop"],
            "profile_notes": "कार्य-त्रुटि का डर और नींद-ऊर्जा चक्र दोनों खराब हैं।",
            "phq": {
                "phq_q3_sleep": 3,
                "phq_q4_fatigue": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q4_trouble_relaxing": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "नींद पूरी उलट गई है",
                    "score_hint": 3,
                    "rationale": "गंभीर नींद-अनियमितता।",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 4,
                    "text_span": "ध्यान टूट जाता है",
                    "score_hint": 2,
                    "rationale": "कॉल के दौरान ध्यान टूटना।",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "नौकरी चली जाएगी",
                    "score_hint": 2,
                    "rationale": "भविष्य-आधारित नुकसान का डर।",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 6,
                    "text_span": "दिमाग आराम करना भूल गया है",
                    "score_hint": 2,
                    "rationale": "आराम न कर पाने का स्पष्ट बयान।",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "शिफ्ट-आधारित थकान और नौकरी खोने की चिंता का मिश्रण।",
            "confidence": {
                "high": ["phq_q3_sleep", "phq_q7_concentration", "gad_q7_afraid"],
                "low": ["gad_q1_nervous", "phq_q4_fatigue"],
            },
        },
        {
            "patient_id": "MV-P029",
            "conversation_id": "MV-C146",
            "language": "hinglish",
            "age": 25,
            "occupation": "software engineer",
            "context": "recent breakup and remote work isolation",
            "living_situation": "PG room",
            "support_system": "one close friend from college",
            "assistant_turns": [
                "Pichhle do hafton mein sabse heavy kya lag raha hai?",
                "Ye zyada overthinking hai, low feel karna hai, ya dono saath chal rahe hain?",
                "Jab aisa thought aata hai ki sab mute ho jaye, uska matlab sirf band ho jana lagta hai ya khud ko hurt karne jaisa bhi lagta hai?",
            ],
            "user_turns": [
                "Breakup ke baad se sab normal act karta hoon, but andar se kaafi down feel hota hai aur kuch bhi interesting nahi lagta.",
                "Raat ko thoughts band hi nahi hote. Kabhi-kabhi lagta hai bas sab mute ho jaye aur mujhe kuch feel hi na karna pade.",
                "Main khud ko hurt nahi karna chahta, but woh line dimag mein aa jaati hai when it gets too much.",
            ],
            "disclosure_style": "masking_then_passive_safety",
            "nuance_tags": ["breakup", "anhedonia", "passive safety cue"],
            "profile_notes": "Hinglish case where safety risk shows up through metaphor rather than direct terms.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 2,
                "phq_q3_sleep": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "andar se kaafi down feel hota hai",
                    "score_hint": 2,
                    "rationale": "Direct low mood in Hinglish.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "kuch bhi interesting nahi lagta",
                    "score_hint": 2,
                    "rationale": "Loss of interest phrased naturally.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 4,
                    "text_span": "bas sab mute ho jaye",
                    "score_hint": 1,
                    "rationale": "Passive shutdown wish needing review.",
                },
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 4,
                    "text_span": "thoughts band hi nahi hote",
                    "score_hint": 2,
                    "rationale": "Cannot stop worrying thoughts.",
                },
            ],
            "safety": {"level": "review", "cues": ["passive_shutdown_language"]},
            "annotator_notes": "Review-level safety cue expressed through muted-language metaphor.",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q2_low_mood", "phq_q9_self_harm"],
                "low": ["gad_q4_trouble_relaxing"],
            },
        },
        {
            "patient_id": "MV-P030",
            "conversation_id": "MV-C147",
            "language": "hinglish",
            "age": 23,
            "occupation": "CA student",
            "context": "exam cycle and repeated comparison with peers",
            "living_situation": "hostel room",
            "support_system": "talks to a sibling at night",
            "assistant_turns": [
                "Abhi sabse zyada kya disturb kar raha hai?",
                "Ye sleep ka issue zyada hai ya focus aur future worry ka combo ban gaya hai?",
                "Jab result ka thought aata hai, body aur mind dono kaise react karte hain?",
            ],
            "user_turns": [
                "Exam prep chal rahi hai but sleep totally off ho gayi hai. Bed pe jaake bhi formulas aur mistakes hi yaad aate rehte hain.",
                "Library mein baithta hoon but focus twenty minutes se zyada tikta hi nahi.",
                "Phir future ka scene dimaag mein loop pe chalne lagta hai ki agar clear nahi hua toh kya hoga.",
            ],
            "disclosure_style": "performance_loop",
            "nuance_tags": ["exam rumination", "sleep onset issue", "future fear"],
            "profile_notes": "Classic performance anxiety with concentration drop.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q7_concentration": 2,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 3,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 2,
                    "text_span": "sleep totally off ho gayi hai",
                    "score_hint": 2,
                    "rationale": "Sleep disruption described clearly.",
                },
                {
                    "item_id": "gad_q2_control_worry",
                    "turn_id": 2,
                    "text_span": "mistakes hi yaad aate rehte hain",
                    "score_hint": 2,
                    "rationale": "Intrusive worry about mistakes.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 4,
                    "text_span": "focus twenty minutes se zyada tikta hi nahi",
                    "score_hint": 2,
                    "rationale": "Direct concentration problem.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 6,
                    "text_span": "agar clear nahi hua toh kya hoga",
                    "score_hint": 2,
                    "rationale": "Future-oriented catastrophic fear.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "High exam anxiety without safety cues.",
            "confidence": {
                "high": ["phq_q3_sleep", "phq_q7_concentration", "gad_q3_excessive_worry"],
                "low": ["gad_q1_nervous"],
            },
        },
        {
            "patient_id": "MV-P031",
            "conversation_id": "MV-C148",
            "language": "hinglish",
            "age": 35,
            "occupation": "salon owner",
            "context": "business debt and staff salary pressure",
            "living_situation": "flat above the shop",
            "support_system": "talks to spouse but filters details",
            "assistant_turns": [
                "Pichhle kuch dino se sabse zyada pressure kahan feel ho raha hai?",
                "Jab salon ka stress aata hai, mind worst-case pe chala jata hai ya body pehle react karti hai?",
                "Sleep, irritation, aur relax na kar paana ka pattern kaisa hai?",
            ],
            "user_turns": [
                "Salon ka rent aur staff salary ka pressure itna hai ki subah se hi chest tight lagti hai.",
                "Customer cancel kare toh seedha worst-case chalu ho jata hai, aur main sab pe irritate ho jati hoon.",
                "Raat ko body tired hoti hai but mind settle nahi hota, so proper rest milta hi nahi.",
            ],
            "disclosure_style": "body_then_catastrophe",
            "nuance_tags": ["debt pressure", "irritability", "insomnia"],
            "profile_notes": "Mixed bodily anxiety and business-catastrophe thinking.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q1_nervous": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q6_irritability": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q1_nervous",
                    "turn_id": 2,
                    "text_span": "chest tight lagti hai",
                    "score_hint": 2,
                    "rationale": "Physical anxiety cue.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 4,
                    "text_span": "seedha worst-case chalu ho jata hai",
                    "score_hint": 2,
                    "rationale": "Rapid catastrophic thinking.",
                },
                {
                    "item_id": "gad_q6_irritability",
                    "turn_id": 4,
                    "text_span": "main sab pe irritate ho jati hoon",
                    "score_hint": 2,
                    "rationale": "Clear irritability.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 6,
                    "text_span": "proper rest milta hi nahi",
                    "score_hint": 2,
                    "rationale": "Sustained sleep disturbance.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Financial anxiety with strong body cue and irritability.",
            "confidence": {
                "high": ["gad_q1_nervous", "gad_q6_irritability", "gad_q7_afraid"],
                "low": ["phq_q4_fatigue"],
            },
        },
        {
            "patient_id": "MV-P032",
            "conversation_id": "MV-C149",
            "language": "hinglish",
            "age": 27,
            "occupation": "content creator",
            "context": "online criticism and inconsistent work cycle",
            "living_situation": "rented room",
            "support_system": "friend group online but increasingly withdrawn",
            "assistant_turns": [
                "Abhi sabse bada change kya notice ho raha hai?",
                "Ye zyada interest chala jana hai, low self-worth hai, ya logon se bachna zyada ho raha hai?",
                "Meals, room se bahar nikalna, aur kaam start karna kitna difficult ho gaya hai?",
            ],
            "user_turns": [
                "Videos banana pehle fun lagta tha, ab camera on karne ka bhi mann nahi karta. Bas postpone karta rehta hoon.",
                "Comments dekhke instantly lagta hai main enough nahi hoon and sab fake lagne lagta hai.",
                "Uske baad room mein hi rehta hoon, meals skip ho jaati hain, aur low feel karta hoon.",
            ],
            "disclosure_style": "comparison_triggered_shutdown",
            "nuance_tags": ["anhedonia", "worthlessness", "social withdrawal"],
            "profile_notes": "Criticism sensitivity drives withdrawal and appetite change.",
            "phq": {
                "phq_q1_anhedonia": 3,
                "phq_q2_low_mood": 2,
                "phq_q5_appetite": 2,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 2,
                    "text_span": "camera on karne ka bhi mann nahi karta",
                    "score_hint": 3,
                    "rationale": "Strong loss of interest in usual activity.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "main enough nahi hoon",
                    "score_hint": 2,
                    "rationale": "Direct low self-worth phrase.",
                },
                {
                    "item_id": "phq_q5_appetite",
                    "turn_id": 6,
                    "text_span": "meals skip ho jaati hain",
                    "score_hint": 2,
                    "rationale": "Appetite/eating reduction.",
                },
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 6,
                    "text_span": "low feel karta hoon",
                    "score_hint": 2,
                    "rationale": "Direct low mood wording.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Depression-leaning Hinglish case with criticism trigger.",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q5_appetite", "phq_q6_worthlessness"],
                "low": ["gad_q1_nervous", "phq_q7_concentration"],
            },
        },
        {
            "patient_id": "MV-P033",
            "conversation_id": "MV-C150",
            "language": "hinglish",
            "age": 24,
            "occupation": "BPO associate",
            "context": "night process, QA checks, and schedule drift",
            "living_situation": "shared flat",
            "support_system": "cousin in the same city",
            "assistant_turns": [
                "Recent days mein sabse zyada kya off lag raha hai?",
                "Ye body ki restlessness zyada hai, sleep issue hai, ya job nikalne ka thought loop?",
                "Shift ke baad body aur mind kitni der tak alert mode mein rehte hain?",
            ],
            "user_turns": [
                "Night process mein kaam karte karte body pura restless rehta hai. Calls ke beech bhi pair hilte rehte hain.",
                "Shift khatam hone ke baad bhi seedha sleep nahi aati because dimaag abhi bhi alert mode mein hota hai.",
                "Choti si QA mistake se lagta hai job nikal jayegi, so worry loop chalta rehta hai.",
            ],
            "disclosure_style": "body_activation",
            "nuance_tags": ["restlessness", "night shift", "job loss fear"],
            "profile_notes": "Very clear GAD-like restlessness and threat anticipation.",
            "phq": {
                "phq_q3_sleep": 2,
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q2_control_worry": 1,
                "gad_q3_excessive_worry": 2,
                "gad_q4_trouble_relaxing": 2,
                "gad_q5_restlessness": 2,
                "gad_q7_afraid": 2,
            },
            "evidence": [
                {
                    "item_id": "gad_q5_restlessness",
                    "turn_id": 2,
                    "text_span": "pair hilte rehte hain",
                    "score_hint": 2,
                    "rationale": "Clear physical restlessness.",
                },
                {
                    "item_id": "gad_q4_trouble_relaxing",
                    "turn_id": 4,
                    "text_span": "alert mode mein hota hai",
                    "score_hint": 2,
                    "rationale": "Cannot wind down after shift.",
                },
                {
                    "item_id": "phq_q3_sleep",
                    "turn_id": 4,
                    "text_span": "seedha sleep nahi aati",
                    "score_hint": 2,
                    "rationale": "Sleep onset problem.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 6,
                    "text_span": "job nikal jayegi",
                    "score_hint": 2,
                    "rationale": "Fear of significant negative outcome.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Night-shift anxiety with strong body-based evidence.",
            "confidence": {
                "high": ["gad_q4_trouble_relaxing", "gad_q5_restlessness", "gad_q7_afraid"],
                "low": ["phq_q4_fatigue", "gad_q2_control_worry"],
            },
        },
        {
            "patient_id": "MV-P034",
            "conversation_id": "MV-C151",
            "language": "hinglish",
            "age": 26,
            "occupation": "newly relocated teacher",
            "context": "marriage-related move to a new city",
            "living_situation": "with spouse and in-laws",
            "support_system": "talks to sister secretly at night",
            "assistant_turns": [
                "Pichhle kuch hafton mein sabse zyada kya feel ho raha hai?",
                "Ye loneliness zyada hai, low mood hai, ya future fit-in karne ka stress bhi saath hai?",
                "Interest, crying, aur future ke thought pattern kaise change hue hain?",
            ],
            "user_turns": [
                "Shaadi ke baad new city aayi hoon and sab theek bolti hoon, but mostly lonely feel hota hai.",
                "Jo cheezein pehle excite karti thi unmein interest kam ho gaya hai, aur bina reason aansu aa jate hain.",
                "Future ko leke bhi tension rehti hai ki main yahan fit ho paungi ya nahi.",
            ],
            "disclosure_style": "polite_masking",
            "nuance_tags": ["loneliness", "anhedonia", "fit-in worry"],
            "profile_notes": "Socially polite presentation with underlying loneliness and worry.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 2,
                "phq_q4_fatigue": 1,
            },
            "gad": {
                "gad_q1_nervous": 1,
                "gad_q3_excessive_worry": 1,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "mostly lonely feel hota hai",
                    "score_hint": 2,
                    "rationale": "Loneliness and low mood phrasing.",
                },
                {
                    "item_id": "phq_q1_anhedonia",
                    "turn_id": 4,
                    "text_span": "interest kam ho gaya hai",
                    "score_hint": 2,
                    "rationale": "Loss of interest in earlier enjoyable activities.",
                },
                {
                    "item_id": "gad_q7_afraid",
                    "turn_id": 6,
                    "text_span": "fit ho paungi ya nahi",
                    "score_hint": 1,
                    "rationale": "Mild future-oriented worry about adjustment.",
                },
            ],
            "safety": {"level": "none", "cues": []},
            "annotator_notes": "Adjustment case with sadness and mild anxiety.",
            "confidence": {
                "high": ["phq_q1_anhedonia", "phq_q2_low_mood"],
                "low": ["phq_q4_fatigue", "gad_q3_excessive_worry"],
            },
        },
        {
            "patient_id": "MV-P035",
            "conversation_id": "MV-C152",
            "language": "hinglish",
            "age": 22,
            "occupation": "startup intern",
            "context": "high-pressure internship and impostor feelings",
            "living_situation": "shared hostel",
            "support_system": "messages one cousin when overwhelmed",
            "assistant_turns": [
                "Abhi dimag pe sabse zyada kya chal raha hai?",
                "Jab mistake hoti hai, uske baad thoughts kis direction mein jaate hain?",
                "Jab aap kehte ho disappear karne ka thought aata hai, kya wo escape jaisa hai ya self-harm jaisa bhi lagta hai?",
            ],
            "user_turns": [
                "Office mein sab smart lagte hain and mujhe constantly feel hota hai ki main bas pretend kar raha hoon.",
                "Ek mistake ho jaaye toh pura din usi pe atka rehta hoon, aur kabhi lagta hai sab log better off honge if I just disappear from the team.",
                "I am not planning anything, but that thought makes me realize things are getting darker than usual.",
            ],
            "disclosure_style": "impostor_to_passive_safety",
            "nuance_tags": ["impostor syndrome", "self-blame", "passive burden thought"],
            "profile_notes": "Review-level safety phrasing inside workplace-worthlessness language.",
            "phq": {
                "phq_q2_low_mood": 1,
                "phq_q6_worthlessness": 2,
                "phq_q7_concentration": 2,
                "phq_q9_self_harm": 1,
            },
            "gad": {
                "gad_q2_control_worry": 2,
                "gad_q3_excessive_worry": 2,
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 2,
                    "text_span": "main bas pretend kar raha hoon",
                    "score_hint": 2,
                    "rationale": "Strong impostor-style self-worth concern.",
                },
                {
                    "item_id": "phq_q7_concentration",
                    "turn_id": 4,
                    "text_span": "pura din usi pe atka rehta hoon",
                    "score_hint": 2,
                    "rationale": "Cognitive fixation affecting focus.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 4,
                    "text_span": "disappear from the team",
                    "score_hint": 1,
                    "rationale": "Passive disappearance language.",
                },
            ],
            "safety": {"level": "review", "cues": ["passive_disappearance", "burden_language"]},
            "annotator_notes": "Review-level case tied to impostor thoughts and burden framing.",
            "confidence": {
                "high": ["phq_q6_worthlessness", "phq_q7_concentration", "phq_q9_self_harm"],
                "low": ["phq_q2_low_mood", "gad_q7_afraid"],
            },
        },
        {
            "patient_id": "MV-P036",
            "conversation_id": "MV-C153",
            "language": "hinglish",
            "age": 21,
            "occupation": "college athlete",
            "context": "career-threatening injury and identity loss",
            "living_situation": "sports hostel",
            "support_system": "coach and one teammate",
            "assistant_turns": [
                "Abhi sabse zyada kya toot sa gaya lag raha hai?",
                "Jab career khatam hone ka thought aata hai, tab aapke mind mein exactly kya aata hai?",
                "Balcony wala thought ek passing flash tha ya us waqt jump karne ka risk real lag raha tha?",
            ],
            "user_turns": [
                "Injury ke baad training band hai and tab se mood kaafi crash ho gaya hai. Din bhar energy low and body heavy lagti hai.",
                "Kabhi-kabhi lagta hai agar ye career waise hi khatam ho raha hai toh mere rehne ka point kya hai.",
                "Last week balcony pe khade hoke socha tha ki jump kar doon, phir coach ko call kiya. Tab se thoughts thode kam hue hain but aaye the.",
            ],
            "disclosure_style": "identity_loss_to_specific_risk",
            "nuance_tags": ["injury grief", "worthlessness", "specific suicide thought"],
            "profile_notes": "Urgent Hinglish safety case with a specific jump thought and help-seeking after it.",
            "phq": {
                "phq_q1_anhedonia": 2,
                "phq_q2_low_mood": 3,
                "phq_q4_fatigue": 2,
                "phq_q6_worthlessness": 2,
                "phq_q9_self_harm": 3,
            },
            "gad": {
                "gad_q7_afraid": 1,
            },
            "evidence": [
                {
                    "item_id": "phq_q2_low_mood",
                    "turn_id": 2,
                    "text_span": "mood kaafi crash ho gaya hai",
                    "score_hint": 3,
                    "rationale": "Severe low mood language.",
                },
                {
                    "item_id": "phq_q4_fatigue",
                    "turn_id": 2,
                    "text_span": "energy low and body heavy lagti hai",
                    "score_hint": 2,
                    "rationale": "Strong fatigue statement.",
                },
                {
                    "item_id": "phq_q6_worthlessness",
                    "turn_id": 4,
                    "text_span": "mere rehne ka point kya hai",
                    "score_hint": 2,
                    "rationale": "Existential worthlessness cue.",
                },
                {
                    "item_id": "phq_q9_self_harm",
                    "turn_id": 6,
                    "text_span": "balcony pe khade hoke socha tha ki jump kar doon",
                    "score_hint": 3,
                    "rationale": "Specific self-harm thought requiring urgent escalation.",
                },
            ],
            "safety": {"level": "urgent", "cues": ["specific_jump_thought", "recent_near_action"]},
            "annotator_notes": "Urgent safety case with specific method and recent timing.",
            "confidence": {
                "high": ["phq_q2_low_mood", "phq_q9_self_harm", "phq_q6_worthlessness"],
                "low": ["gad_q7_afraid"],
            },
        },
    ]


def score_band(total: int) -> str:
    if total <= 4:
        return "minimal"
    if total <= 9:
        return "mild"
    if total <= 14:
        return "moderate"
    return "moderate_to_high"


def zero_labels(item_ids: list[str], overrides: dict[str, int]) -> dict[str, int]:
    values = {item_id: 0 for item_id in item_ids}
    values.update(overrides)
    return values


def build_turns(language: str, assistant_turns: list[str], user_turns: list[str]) -> list[dict]:
    turns = []
    turn_id = 1
    for assistant_text, user_text in zip(assistant_turns, user_turns):
        turns.append(
            {
                "turn_id": turn_id,
                "speaker": "assistant",
                "text": assistant_text,
                "language_tag": language,
            }
        )
        turn_id += 1
        turns.append(
            {
                "turn_id": turn_id,
                "speaker": "user",
                "text": user_text,
                "language_tag": language,
            }
        )
        turn_id += 1
    return turns


def build_profile(spec: dict) -> dict:
    phq_labels = zero_labels(PHQ_IDS, spec["phq"])
    gad_labels = zero_labels(GAD_IDS, spec["gad"])
    return {
        "patient_id": spec["patient_id"],
        "language": spec["language"],
        "age": spec["age"],
        "occupation": spec["occupation"],
        "background_profile": {
            "context": spec["context"],
            "living_situation": spec["living_situation"],
            "support_system": spec["support_system"],
        },
        "symptom_profile": {
            "depression_level": score_band(sum(phq_labels.values())),
            "anxiety_level": score_band(sum(gad_labels.values())),
        },
        "disclosure_style": spec["disclosure_style"],
        "nuance_tags": spec["nuance_tags"],
        "notes": spec["profile_notes"],
    }


def build_conversation(spec: dict, index: int) -> dict:
    phq_labels = zero_labels(PHQ_IDS, spec["phq"])
    gad_labels = zero_labels(GAD_IDS, spec["gad"])
    evidence_spans = []
    annotators = ["Yash", "Ritwij"]
    for offset, evidence in enumerate(spec["evidence"], start=1):
        evidence_spans.append(
            {
                "span_id": f"E{offset}",
                "questionnaire": "PHQ9" if evidence["item_id"].startswith("phq_") else "GAD7",
                "item_id": evidence["item_id"],
                "turn_id": evidence["turn_id"],
                "text_span": evidence["text_span"],
                "polarity": "present",
                "score_hint": evidence["score_hint"],
                "annotator": evidence.get("annotator", annotators[(offset - 1) % 2]),
                "rationale": evidence["rationale"],
            }
        )

    review_status = spec.get("review_status")
    if not review_status:
        review_status = "consensus_final" if index % 2 else "double_annotated"

    return {
        "conversation_id": spec["conversation_id"],
        "patient_id": spec["patient_id"],
        "language": spec["language"],
        "age": spec["age"],
        "occupation": spec["occupation"],
        "background_profile": {
            "context": spec["context"],
            "living_situation": spec["living_situation"],
        },
        "symptom_profile": {
            "depression_level": score_band(sum(phq_labels.values())),
            "anxiety_level": score_band(sum(gad_labels.values())),
        },
        "conversation_turns": build_turns(spec["language"], spec["assistant_turns"], spec["user_turns"]),
        "evidence_spans": evidence_spans,
        "phq9_item_labels": phq_labels,
        "gad7_item_labels": gad_labels,
        "safety_flag": spec["safety"],
        "annotator_notes": spec["annotator_notes"],
        "confidence_notes": {
            "high_confidence_items": spec["confidence"]["high"],
            "low_confidence_items": spec["confidence"]["low"],
        },
        "generation_source": "curated_seed_scaleup_v1",
        "review_status": review_status,
    }


def main() -> int:
    scenarios = scaleup_scenarios()
    profiles = [build_profile(spec) for spec in scenarios]
    conversations = [build_conversation(spec, index) for index, spec in enumerate(scenarios, start=1)]

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    profiles_path = SEED_DIR / "patient_profiles_scaleup.json"
    conversations_path = SEED_DIR / "conversations_scaleup.json"
    profiles_path.write_text(json.dumps(profiles, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    conversations_path.write_text(json.dumps(conversations, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(profiles_path)
    print(conversations_path)
    print(f"profiles={len(profiles)} conversations={len(conversations)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
