#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MANOVARTA_MODEL_PROVIDER="${MANOVARTA_MODEL_PROVIDER:-local}"
export MANOVARTA_CHAT_PROVIDER="${MANOVARTA_CHAT_PROVIDER:-vertex}"
export MANOVARTA_EXTRACTION_PROVIDER="${MANOVARTA_EXTRACTION_PROVIDER:-local}"
export MANOVARTA_SAFETY_PROVIDER="${MANOVARTA_SAFETY_PROVIDER:-local}"
export MANOVARTA_EXTRACTION_MODEL="${MANOVARTA_EXTRACTION_MODEL:-/models/aya-expanse-8b}"
export MANOVARTA_LOCAL_EXTRACTION_ADAPTER="${MANOVARTA_LOCAL_EXTRACTION_ADAPTER:-/models/aya_bundle}"
export MANOVARTA_LOCAL_LOAD_IN_4BIT="${MANOVARTA_LOCAL_LOAD_IN_4BIT:-true}"
export MANOVARTA_ASYNC_SCORING_ENABLED="${MANOVARTA_ASYNC_SCORING_ENABLED:-true}"
export MANOVARTA_ASYNC_SCORING_DIR="${MANOVARTA_ASYNC_SCORING_DIR:-${ROOT}/artifacts/async_scoring}"

cd "${ROOT}"
python3 tools/process_async_score_queue.py "$@"
